### ISSUE TITLE
No SquasfFS is created

### ISSUE THREAD

**Issue by ranseyer** [kamilion/customizer#100]
My System Ubuntu 14.04.2 as Host and an brandnew 14.04.2 ISO for remastering without changes. Only remastered as it is for the test. Customizer is the latest version: bb21e29c21501b89e411ccbb8cfc716911a2051d

I got this error Message, and there is no squash-fs created. (i tried gzip and xz compression)
![5](https://cloud.githubusercontent.com/assets/3889328/7806333/dd686b12-037f-11e5-9b7b-9a8fb70727d3.jpg)
Because of the missing squashfs i got no ISO...

This one from 19.05. works: d6bd0f676a3c3ea658035ac9190b590d0ab0d1fd (from: pguth; before the merge of pull request)

**Comment by ghost** [comment]
I will check latest Customizer from **master** branch soon. Although, I will be testing only with 32-bit machine running Xubuntu 14.04 from my side.

**Comment by ghost** [comment]
Confirmed this issue from my side as well. I think something went wrong at commit 8ca43ae whose difference with 60045d5 is only the `misc.py` file after line 133.

That's all I could tell from my side (I am not capable to fix the code).

Anyway, the last working Customizer release is commit 60045d5 which has been tested just now.

**Comment by ghost** [comment]
Confirmed fix using latest release from **master** branch. Tested working using Xubuntu 14.04 32-bit for both host system and ISO image.

The squashfs works properly again from commit 1b1535a that has been issued few days ago. Thanks @fluxer for the fix!

**Comment by fluxer** [comment]
@clearkimura 
I broke it - I fix it. :)

**Comment by ranseyer** [comment]
Sorry for the late reaction. I have tested it too, and it works again on my local workstation.

Thank you!
