### ISSUE TITLE
python2-config not found

### ISSUE THREAD

**Issue by Israphel** [kamilion/customizer#101]
make returns that on Ubuntu 14.04 with python2 installed, 'cause the command is python2.7-config

workaround: sudo ln -s /usr/bin/python2.7-config /usr/bin/python2-config

**Comment by fluxer** [comment]
Depending on how Python was build and installed the python2-config symlink may not exist on your system, see the README file shipped with the Python source code (section "Installing multiple versions"). Customizer's build system (tries) to support the default upstream behaviour, most of the distribution quirks (or even user preferences) can be handled properly by overriding make variables.

The workaround is simpler than you think:
`make PREFIX=/usr`
or:
`make PYTHON=python2.7`

Cheers!
