### ISSUE TITLE
Internet connectivity fails in Ubuntu 15.04-based remasters

### ISSUE THREAD

**Issue by thomasstevenson** [kamilion/customizer#103]
Unfortunately it looks like there's another issue with remastering Ubuntu 15.04 in Customizer.

After remastering Ubuntu 15.04 on an Ubuntu 15.04 host system with the latest version of Customizer from the master branch, Internet connectivity fails, at least when using the Live DVD/USB. Although I was able to connect to a Wifi network,  I couldn't get an Internet connection using it. I have checked the Wifi network and have made sure that a stable connection to the Internet was present. I have also checked that it wasn't an issue with Firefox, since no app which connects to the Internet works (eg. Software Center, Totem Video Player).

I haven't made an installation of the remastered distro to confirm whether an Internet connection is possible on a native install, but I will keep you posted when I do.

I have tried remastering the .iso file without any modifications (Open Customizer > Select ISO [ubuntu-15.04-desktop-amd64.iso] >  Rebuild ISO) on an unmodified host (Installed Ubuntu 15.04 and Customizer with its dependencies only) with the same results.

I have only tested this on 64 bit remasters. I haven't had the chance to test in with 32 bit remasters yet.

**Comment by thomasstevenson** [comment]
I've just tried Customizer with a 32 bit version of Ubuntu 15.04 and I can confirm that this issue is still present.
In addition, I have installed a remastered version of Ubuntu 15.04 natively and I'm still not able to use the Internet.

This is the error I see when trying to browse the Web with the remastered version of Ubuntu 15.04:
![screenshot from 2015-06-21 17 13 19](https://cloud.githubusercontent.com/assets/7741618/8272426/ca85ca2a-1839-11e5-861f-a85613607e0a.png)

**Comment by fluxer** [comment]
Please test the 103 branch and let me know how it works for your. I believe I have fixed the issue, testing with Xubuntu right now (the issue was valid for it too).

**Comment by thomasstevenson** [comment]
I have tried the 103 branch and am happy to say that this issue has been fixed.
I have tried using the Internet on the Live DVD & on a native install, and it works perfectly in both cases.

Well done @fluxer!

**Comment by fluxer** [comment]
Thanks for the feedback, I'll merge the branch into master.
