### ISSUE TITLE
/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease dependency missing on Ubuntu 15.04

### ISSUE THREAD

**Issue by luzam** [kamilion/customizer#104]
Hello, 
I tried to compile on Ubuntu 15.04, seems that /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease dependency is missing : 
rm -vf -r  tr/_.qm *.tar.xz
rm -vf -r debian/_.log debian/customizer.substvars \
    debian/customizer debian/files \
    src/gui_ui.py src/gui.py src/main.py \
    data/customizer.policy data/customizer.menu \
    data/customizer.desktop
removed ‘src/gui_ui.py’
removed ‘src/gui.py’
removed ‘src/main.py’
removed ‘data/customizer.policy’
removed ‘data/customizer.menu’
removed ‘data/customizer.desktop’
sed -e 's|@VERSION@|4.1.1 (cefca0d)|' -e 's|@PREFIX@|/usr|g' \
    src/main.py.in > src/main.py
sed -e 's|@PREFIX@|/usr|' -e 's|@ELEVATOR@|pkexec|' \
    data/customizer.menu.in > data/customizer.menu
sed -e 's|@PREFIX@|/usr|' -e 's|@ELEVATOR@|pkexec|' \
    data/customizer.desktop.in > data/customizer.desktop
sed 's|@PREFIX@|/usr|' data/customizer.policy.in > \
    data/customizer.policy
sed -e 's|@VERSION@|4.1.1 (cefca0d)|' -e 's|@PREFIX@|/usr|g' \
    src/gui.py.in > src/gui.py
pyuic4 src/gui.ui -o src/gui_ui.py
pylupdate4 -noobsolete -verbose src/_.py -ts tr/customizer_bg_BG.ts
Updating 'tr/customizer_bg_BG.ts'...
    Found 57 source texts (0 new and 57 already existing)
lrelease tr/customizer_bg_BG.ts
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lrelease': No such file or directory
Makefile:32: recipe for target 'gui' failed
make: *_\* [gui] Error 1

qt5/bin/lrelease is installed by the qttools5-dev-tools
if you want to add this package to the deps.

Thank for your work !
Lucas

**Comment by fluxer** [comment]
The GUI used the Qt4 toolkit, please read https://github.com/clearkimura/Customizer/wiki/First-guide#2-how-to-install-customizer.

Cheers!

**Comment by kamilion** [comment]
Just a note on this issue, ubuntu recently changed the link for lrelease to go to the qt5 library.
We need to call `lrelease-qt4` instead. Issue has been fixed in my branch.

**Comment by ghost** [comment]
This issue is now closed, due to [Ubuntu 15.04 has reached End of Life](https://lists.ubuntu.com/archives/ubuntu-announce/2016-January/000203.html) on February 4, 2016.

**Comment by riccardomanfrin** [comment]
Same annoying issue in U 18.04 
Had to create `/usr/lib/qt5/bin/lrelease` executable bash script

```
#!/bin/bash
echo 5
```
This let me step forward in wireshark build from sources ...
