### ISSUE TITLE
Error while rebuilding the ISO

### ISSUE THREAD

**Issue by elacheche** [kamilion/customizer#106]
When I use `sudo customizer -r` I get the following output:

```
* Rebuilding ISO...
  => Checking
  => Doing sanity checks
  => Gathering information
  => Cleaning up
  => Updating initramfs
update-initramfs: Generating /boot/initrd.img-3.13.0-58-generic
  => Copying boot files
  => Extracting casper UUID
gzip: d.img-3.13.0-58-generic.gz: No such file or directory
cpio: premature end of archive
* SUBPROCESS: Command '/usr/sbin/chroot /home/anis/Sabily/Customizer/workDir/FileSystem zcat d.img-3.13.0-58-generic |  cpio --quiet -id conf/uuid.conf' returned non-zero exit status 1

```

Why it's looking for the wrong file?

**Comment by fluxer** [comment]
Because str.lstrip("<characters>") behaves like like str.replace("<characters>", "<newcharacters>") except on per-character bases rather than just replacing the whole string, see https://docs.python.org/2/library/stdtypes.html#str.lstrip for more details along with the commit reference bellow.

**Comment by elacheche** [comment]
Amazing! I was trying to understand that line to fix the problem :) Thank you fix fixing it :)
