### ISSUE TITLE
No updates in a while.

### ISSUE THREAD

**Issue by ndemon** [kamilion/customizer#11]
Hasn’t been updated in a while.

**Comment by kamilion** [comment]
What needs updating? Does it fail on 16.10?

**Comment by ndemon** [comment]
EDIT: was looking in old area.

**Comment by kamilion** [comment]
No problem. If you run into anything, let me know.
Unicode's still a problem because python2.7 is being used. Most of the code is python3 clean.
Waiting for QT 5.7 to be more widely deployed before I start porting from qt4 to qt5.
