### ISSUE TITLE
Working with projects

### ISSUE THREAD

**Issue by fredbcode** [kamilion/customizer#112]
Hello,

there is a way, or there will be a way in the near future, to work with different projects ?
I mean something like: One directory for distribution, 1 Another directory for distribution 2, etc 
And a menu for select the project, clone, etc

**Comment by fredbcode** [comment]
Sorry, I missed #38
Just to be more clear, I think about something like that http://www.korben.info/wp-content/uploads/2010/06/cap-2010-06-28-à-07.05.57.png
In ubukey project there is also a button "clone" very useful for making tests without stress :)

**Comment by ghost** [comment]
@fredbcode 
You can always amend the first comment by clicking on the "pencil" icon at right corner of the comment area. Please give better description of your suggestion in the first comment.

P.S.: Combine the second comment into the first one. Also, better description of your suggestion is needed for anyone not having knowledge about, for example, the "clone" button in ubukey.

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.

For future issues, submit to official fork: https://github.com/kamilion/customizer 

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
