### ISSUE TITLE
Ubuntu 15.10 Support

### ISSUE THREAD

**Issue by AwlsomeAlex** [kamilion/customizer#113]
Hello, does Customizer have or will have Ubuntu 15.10 support?

**Comment by ghost** [comment]
@AwlsomeAlex 
You have asked similar question in earlier issue #107 

> Hello, I would like to know the Compatibility of Customizer, and how new it is, for example, does it run and create Ubuntu 15.04 or even 15.10 BETA/ALPHA, and [...]

The difference between Beta and Final releases would be just bug fixes. If you have already tried with the Beta release, why would the Final release not working?

In fact, before the last pull request #110 was merged, @kamilion [did a lot of effort](https://github.com/clearkimura/Customizer/pull/109#issuecomment-137333654) to test the releases for both 32-bit and 64-bit ISO images, including 15.10 Beta releases. Hasn't this been answered?

**Comment by AwlsomeAlex** [comment]
Opps, I just realized that. Terribly sorry.
