### ISSUE TITLE
Improvise debug system

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#159]
This is probably the first thing to do, before trying to fix or improve existing features in this project.

At present, I find that debug messages are quite verbose to be read and sometimes not easy to figure out the source of error. Following are proposed changes that have been identified.

**A. Standardize debug variable**

In `src/lib/misc.py`, multiple `_DEBUG` variables have been introduced when adding support for Python 3 last year. These are actually redundant or duplicates of existing code, since there is a standard variable and conditional defined in `src/lib/message.py`.

    ```
    import lib.message as message

    CMD_DEBUG = False
    CHROOT_DEBUG = False
    FILE_DEBUG = False
    MOUNT_DEBUG = False
    # ^ remove these variables

    ...
    # ^ then, remove all instances of `if *_DEBUG` for good,
    #  because `message.py` has defined `sub_debug(msg)` function
    #  with `if DEBUG` conditional already 
    ```

**B. Dedicate debug message**

Some debug messages are dedicated to certain functions. Instead of human language a.k.a. English, use function name itself to locate the source of message easily.

    ```
    def read_file(sfile):
        if FILE_DEBUG:
        # ^ this line is redundant
            message.sub_debug('Reading entire file', sfile)
        #                      ^ this is not easy to locate
    ...
            message.sub_debug('read_file', sfile)
        #                      ^ this is easier to locate because
        #                        using function name itself
    ...
    def system_command(command, shell=False, cwd=None, env=None):
        message.sub_debug('Executing system command', command)
        #                  ^ this is not easy to locate
    ...
        message.sub_debug('system_command', command)
        #                  ^ use function name itself
    ```

**C. Accurate debug message**

Some debug messages are tricky and not easy to guess where it will appear. In particular, debug messages that supposed to appear in host Terminal and chroot Terminal are most confusing.

I did some trials and errors before managed to distinguish messages that appear in two instances of Terminal. Relevant comment and debug messages shall be added to each section.

    ```
    if output:
        # This will be shown in host Terminal
        message.sub_debug('Enter chroot from host')
        out = get_output(chroot_command)
        message.sub_debug('Exit chroot to host')
    else:
        # This will be shown in chroot Terminal
        message.sub_debug('Enter chroot')
        system_command(chroot_command, shell=shell, \
            env=environment, cwd=cwd)
        message.sub_debug('Exit chroot')
    ```

Notice that verbs are revised to its basic words (without any tenses or prefixes) to be simple and easy to understand. Use simple phrases that are commonly used in software development, such as "File not found" instead of conventional English "Configuration file does not exist".

    $ sudo customizer-gui 
    [sudo] password for trusty: 
    * Configuration file does not exist: /etc/customizer.conf
    * Read Configuration file: /etc/customizer.conf
    ...

    $ sudo customizer-gui 
    [sudo] password for trusty: 
    * File not found: /etc/customizer.conf
    * Read from: /etc/customizer.conf
    ...

The debug messages are supposed to guide and help us to identify software issues; using conventional English will make debug messages more verbose and will distract our focus.

**D. Missing message and errata**

Similar to 3.x release, a warning message should appear in chroot Terminal, to remind users to use `exit` command to leave chroot. Following C., I managed to figure out this also.

    ```
    else:
        # This will be shown in chroot Terminal
        message.sub_debug('Enter chroot')
        message.warning('IMPORTANT: To leave chroot, type \'exit\'')
        #                ^ bring back this message
        system_command(chroot_command, shell=shell, \
            env=environment, cwd=cwd)
        message.sub_debug('Exit chroot')
    ```

There is at least one instance that debug message tells something different or has nothing to do with the function itself.

    ```
    def change_work_dir():
        message.sub_debug('Attempting to change hostname...')
        #                  ^ this tells different from its function
    ```

**E. Remove duplicate**

Some debug messages are duplicate of existing messages. I couldn't find any good reason to have two similar lines of code telling the same information. Or, revise debug message to be simple.

    ```
    if os.path.ismount(sdir):
        message.sub_debug('Unmounting -f -l', sdir)
        #                  ^ remove this duplicate
        message.sub_debug('Unmount', sdir)
        #                  ^ or simplify message
        system_command((umount, '-f', '-l', sdir))
        #       ^ this output is visible even without debug option
    ```

**F. Enable debug from GUI**

This is probably a feature request that have never been (or never will be) filed by end users. I think I read somewhere that they might have asked how to see debug messages while running Customizer GUI, and not command line (there is debug option for command line, yet...).

I suppose this is feasible, although first I must understand read-write operation to `.conf` file via GUI. Because this requires different focus and effort, this will be at very low priority.

Or, this might be *not* useful to end users. Even such option has been added, another challenge is how those debug messages could be easily included or copied when submitting a new issue.

Meanwhile, there is `CATCH` variable found in `src/lib/misc.py` which seems to be parsing some messages via GUI already. This means "enable debug from GUI" may be a duplicate feature.

**Except for F., all proposed changes must be resolved in milestone 4.1.5 to prepare for any significant changes before reaching 4.2.0.**

**Comment by kamilion** [comment]
The various debug variables are there because some of them are *VERY* chatty, and only really needed when I'm going through verification tests after merging changes in.

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.
