### ISSUE TITLE
Final checklist for interim maintainer

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#161]
This is probably the last thing to check for "old stable".

The following are planned changes:

status - todo
`[OK]` - delete `gambas3` branch (obsolete, already available as tagged release 3.2.3)
`[OK]` - delete `translatable-about` branch (obsolete, after resolving translatable 'About')
`[OK]` - delete `forkout` branch (no longer relevant)
`[OK]` - delete `fix*` branches (no longer relevant after respective pull request)
`[OK]` - make last pull request to merge changes for resolving hardcoding with a quick fix
`[OK]` - include last update with grace period in README.md (to notify unmaintained PPA that this repository is deprecated, without having to directly contact the maintainers)

From README.md:

> A grace period of 2 weeks shall be effective from day of last commit, to allow any updates within GitHub network or repositories. When the grace period ends, this repository will be permanently deleted. Grace period will end on 2017-02-11 (Feb 11, 2017)

**Last todo on 2017.02.11:**

Delete this repository "old stable" after grace period (cancelled, or may be not?)

**Updated on 2017.01.30:**

As Jan 30, 2017, there is only `master` branch in "old stable" repository and all issues have been closed due to "old stable" being deprecated. It's "very clean" now.

There was change in plan at last minute after grace period is announced. Transfer this repo to fork maintainer, and that's the end of my role.

But ops, transfer has failed due to existence of fork itself.

**Updated on 2017.01.31:**

As Jan 31, 2017, official fork was entirely removed. Most issues I had closed had noted link to official fork, which now becomes invalid (noted P.S.: for all 28 closed issues listed in "pulse" section).

This "old stable" repo will be transferred to fork maintainer.

**Final note:**

I have been using GitHub for collaborating to this project since late 2011 to this date. Since I don't use GitHub for anything else, I'd probably remove my GitHub account when the grace period ends.

Until then, I may respond to @mention if any.

**Comment by ghost** [comment]
@kamilion 
I have initiated transfer of this "old stable" repo to you. Waiting for your accept.

**Comment by kamilion** [comment]
@clearkimura Transfer confirmed. Thanks for all of your contributions; may the seas you sail be calm and the winds be fair

**Comment by kamilion** [comment]
@clearkimura Are you comfortable leaving the wiki images with dropbox, or shall I go through and rehost them all?

**Comment by ghost** [comment]
@kamilion
I had forgotten about that until now. I think I have only used Dropbox to
show screenshots and nothing else. Anyway, I think it's better to rehost
and remove all existing links to the Dropbox. Thanks.

P.S.: Ops, my email was signed by own e-mail address. Removed quoted text.

**Comment by kamilion** [comment]
@clearkimura Okay, I'll try to get that done over the next week or so. Thanks.

**Comment by ghost** [comment]
@kamilion 
For your convenience, I have gathered relevant screenshots (except for 3.2.3 legacy screenshots) used in Customizer Wiki and compressed into tar.gz archive file and uploaded to Dropbox.

You can download screenshots from the following shared link.

https://www.dropbox.com/s/ao7cvah8928on70/screenshot.tar.gz?dl=0

I'll make quick review again, since there might be some dead links or outdated information i.e. `debian/copyright` regarding history of maintainership, since things changed faster than I could notice during the past week.

And that's pretty much all from my side.

**Comment by kamilion** [comment]
@clearkimura Oh, thanks! That helps a lot, I'll grab the image pack right now.
