### ISSUE TITLE
sudo customizer -e (Output) - Pls Help!

### ISSUE THREAD

**Issue by Timtech4u** [kamilion/customizer#165]
ubuntu@ip-172-31-39-22:~$ sudo customizer -e
* Read Configuration file: /etc/customizer.conf
* Extracting...
  => Removing: /home/FileSystem
  => Removing: /home/ISO
  => Creating: /home/FileSystem
  => Creating: /home/ISO
  => Creating mount directory
  => Mounting ISO: /home/ubuntu/ubuntu-16.04.1-desktop-amd64.iso
  => Checking ISO
  => Unsquashing filesystem
Parallel unsquashfs: Using 2 processors
Lseek failed because Invalid argument
read_block: failed to read block @0x389b800974effea0
read_uids_guids: failed to read id table block
FATAL ERROR:failed to uid/gid table
  => Unmounting: /media/pgefgi
  => Removing: /media/pgefgi
* SUBPROCESS: Command '('/usr/bin/unsquashfs', '-f', '-d', '/home/FileSystem', '/media/pgefgi/casper/filesystem.squashfs')' returned non-zero exit status 1

**Comment by kamilion** [comment]
More information please...
CPU Architecture, amount of RAM, amount of free disk space...

From a quick google on "Lseek failed because Invalid argument", this appears to be a corrupt ISO.
Check your source ISO against the SHA1SUM and redownload it?

**Comment by Timtech4u** [comment]
Thanks, I downloaded a new .iso and it worked.
