### ISSUE TITLE
Refer to "the fork" for 64 bit

### ISSUE THREAD

**Issue by niccokunzmann** [kamilion/customizer#167]
The README.md states

> Future development has moved to the fork, which aims to migrate the code to Python 3 and Qt 5. The fork is optimized for remastering 64-bit ISO images and will support newer releases of Ubuntu.

I would like to see a link to the fork there because I can not find it.

**Comment by kamilion** [comment]
This is the fork. The old repo was https://github.com/clearkimura/Customizer/ before it migrated here.
