### ISSUE TITLE
Can't compile/install today's version

### ISSUE THREAD

**Issue by melodie11** [kamilion/customizer#170]
Hello,
I have tried to get the newest version, under Ubuntu 14.04 but I fail compiling it. The output states it misses some Qt5 lib.

> $ make && sudo make install
Using python2.7 to test for PyQT4:
PyQt4 has been found
Using python2.7 to test for PyQT5:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named PyQt5
make: *** [check-pyqt5] Error 1

I tried to install some pyqt5 packages, among the ones available in the repos:
pyqt5-dev-tools pyqt5-dev python3-pyqt5

but this isn't what is expected because it keeps failing. Could you point me in the right direction and add the information to the manual page please? https://github.com/kamilion/customizer/blob/master/docs/manual.md

Here are the outputs from my trials:
http://pastebin.fr/49568

Also, a version without a GUI would be nice, as it's quite easy to use Customizer on a remote server without a X server.

Thanks for your work! 
Best regards,
Mélodie

**Comment by NeunJa** [comment]
I also have this issue at ubuntu 14.04 x32
Could you please help?

also at Ubuntu 16.04 x32 all works fine (after python-pyqt5 installation)

**Comment by kamilion** [comment]
Hm, I'll look into that error; it shouldn't stop the build if it found qt4 but didn't find qt5.
I probably screwed something up in the makefile and didn't test quite enough.

But from your log; you installed the python3 version of the libraries, but didn't tell the makefile to use python3.

You can do this with `make PYTHON=python3`

I'll see what I can do in the makefile to build the CLI without the GUI shell.

**Comment by kamilion** [comment]
partially fixed in development branch, still trying to figure out the makefile statements.

**Comment by kamilion** [comment]
Makefile was altered to not abort if either of the QT checks fail. There will probably be some other indications if QT's actually missing and a user blindly tries anyway.
