### ISSUE TITLE
Invalid ISO

### ISSUE THREAD

**Issue by muzzol** [kamilion/customizer#176]
I got this error when trying to load ubuntu server ISO:
```

# customizer -e -D
* Read Configuration file: /etc/customizer.conf
* Extracting...
  => Creating: /media/sf_isos/customizer-tmp/FileSystem
  => Creating: /media/sf_isos/customizer-tmp/ISO
  => Creating mount directory
  => Mount directory is: /media/DZGr6o
  => Mounting ISO: /media/sf_isos/ubuntu-16.04.2-server-amd64.iso
  => Checking ISO
  => Non-existing path: /media/DZGr6o/casper/filesystem.squashfs
  => Removing: /media/sf_isos/customizer-tmp/FileSystem
  => Removing: /media/sf_isos/customizer-tmp/ISO
  => Unmounting: /media/DZGr6o
  => Removing: /media/DZGr6o
* CUSTOMIZER: ('Invalid ISO', '/media/sf_isos/ubuntu-16.04.2-server-amd64.iso')

```

**Comment by AwlsomeAlex** [comment]
I don't think the Ubuntu Server ISOs are actual live environments which you can edit, but more as an installer like the Ubuntu Minimal ISO. Live Disks would have the Casper directory which would boot it into a live environment, but this only has an Install directory which the filesystem.squash can be found. It looks fairly minimal as well suggesting its only purpose is to install. That is also apparent [here](http://i.imgur.com/M9fqgpX.png) with the only options being "Install" options.

**Comment by kamilion** [comment]
Yeah, customizer can only edit live ISOs -- not alternate ISOs (which are based on debian-installer) of which, the ubuntu-server ISO is a member of, despite not being labeled 'alternate'.

There's a number of other tools that can put together console-only spins, I'd suggest hashicorp's Packer.
https://www.packer.io/

It doesn't work too well for remastering Desktop based images though.
Reopen this issue if you'd like some further recommendations on console-only remasters.
