### ISSUE TITLE
Unable to start xnest

### ISSUE THREAD

**Issue by apinprastya** [kamilion/customizer#177]
Downloaded lastest version 4.1.4-0 and also directly from git clone and unable to start the xnest.
Host using LUbuntu 16.04.01 32bit and the remaster iso also use Lubuntu 16.04.01 32bit.
Host running on top of VirtualBox.
Here the log i have on terminal : 

> apin@apin-VirtualBox:~/cust$ sudo customizer -x
> * Read Configuration file: /etc/customizer.conf
> * Running nested X session...
>   => Checking
>   => Detecting available sessions
>   => Starting Xephyr
>   => Allowing local access to X-server
> non-network local connections being added to access control list
>   => Starting nested X session: /usr/bin/openbox-session
> Openbox-Message: Unable to find a valid menu file "/var/lib/openbox/debian-menu.xml"
> /bin/sh: 1: exec: update-notifier: not found
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> process 2945: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
> See the manual page for dbus-uuidgen to correct this issue.
> process 2943: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
> See the manual page for dbus-uuidgen to correct this issue.
> 
> ** (nm-applet:2943): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> 
> ** (light-locker:2945): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> 
> (light-locker:2945): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch= --binary-syntax --close-stderr': Child process exited with code 1
> process 2942: D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
> See the manual page for dbus-uuidgen to correct this issue.
> process 2945: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file ../../dbus/dbus-message.c line 1340.
> This is normally a bug in some application using the D-Bus library.
> 
> ** (blueman-applet:2942): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
> process 2945: arguments to dbus_message_new_method_call() were incorrect, assertion "path != NULL" failed in file .

**Comment by kamilion** [comment]
Hm, looks to me like this is an actual bug in the ubuntu packages -- have you brought the image up to date with an `apt-get dist-upgrade` before starting xnest, or is this purely with the packages unpacked from the ISO image?

**Comment by kamilion** [comment]
Also, something appears to be amiss with the virtual machine you're using to construct your ISOs with -- something is wrong with your dbus configuration, **your /etc/machine-id is blank**, and the dbus library doesn't know what to do about that.

`D-Bus library appears to be incorrectly set up; failed to read machine uuid: UUID file '/etc/machine-id' should contain a hex string of length 32, not length 0, with no other text
See the manual page for dbus-uuidgen to correct this issue.`

As such, no messages can be passed along the desktop bus; so quite a lot of things are going to be failing, as seen with the errors from light-locker complaining it's unable to save configuration files.

`(light-locker:2945): dconf-WARNING **: failed to commit changes to dconf`

You also appear to have a bluetooth daemon (blueman-applet) running in a virtual machine.

The international keyboard accessibility packages also appear to be unable to communicated with, resulting in further error spam.

`** (blueman-applet:2942): WARNING **: Error retrieving accessibility bus address: `
 `The name org.a11y.Bus was not provided by any .service files`

I've had to deal with DBUS machine IDs in the past,
https://github.com/kamilion/kamikazi-core/blob/a739e038fd0b40036d63e4c680e74738e20e8324/resources/xenial/mods/usr/share/initramfs-tools/scripts/casper-bottom/18kamikazi_restore#L38

so I know the quick solution:
`dbus-uuidgen > /var/lib/dbus/machine-id`
should fix your VM, hopefully.

**Comment by apinprastya** [comment]
> Hm, looks to me like this is an actual bug in the ubuntu packages -- have you brought the image up to date with an apt-get dist-upgrade before starting xnest, or is this purely with the packages unpacked from the ISO image?

I am not sure for doing dist-upgrade but i do the apt-get upgrade. I do the apt update on both the host and the remaster.

> so I know the quick solution:
> dbus-uuidgen > /var/lib/dbus/machine-id
> should fix your VM, hopefully.

This not help, I have the same error. 
My another question, do you think this problem is the host or the remaster?

**Comment by apinprastya** [comment]
Change the host to ubuntu 16.04 fix the problem.

**Comment by kamilion** [comment]
Should be noted -- using `apt-get dist-upgrade` will allow new packages to be installed, `apt-get upgrade` will only upgrade packages that have no new dependencies.

It *DEFINITELY* works on lubuntu -- as that is where I do all of my development from.

Thanks for reporting; let me know if you run into anything else.
