### ISSUE TITLE
Unable to locate package default - installed from git w/installer.py

### ISSUE THREAD

**Issue by dlarue** [kamilion/customizer#184]
Installing on Lubuntu 16.04.3 and ran across runtime errors. First it was with cleaning the directory and not dealing with rfind. I'd originally manually installed packages( git, python-dev, build-essential, pyqt4-dev-tools ). It built and installed without errors but when run I got the errors trying to clean.

I found this thread and run 'sudo python installer.py' and found the 'update from git' option and used "update customizer + update apt requirements" and that solved the problem with clean and was able to expand the filesystem, run a hook to edit some files but when running "build ISO" I got this error:

An error occured while a thread was running:
Type: <type 'exceptions.RuntimeError'>
Details:
E: Unable to locate package default

**Comment by dlarue** [comment]
So I started from scratch, a fresh running Lubuntu 16.04.3 and only installed git before running installer.py as root.  Tried to run the requirements update, didn't work, tried to run update of customizer and requirements both those failed. Ran the gui update and then went back and ran the update customizer and requirements. didn't work and tried over and over using installer.py to get open 1/Run to work. It would fail and not bring up a gui.  I even installed pip and then ran 'sudo pip install python-config' and while it stopped the "install customizer" build error it still would not run..

So I exited and ran make && sudo make install and now I'm running from commandline( customizer-gui ) and it's expanding the ISO filesystem. But it still fails with the dialog noted above..

console output(end of it ) looks like this:
The link /vmlinuz is a damaged link
Removing symbolic link vmlinuz 
 you may need to re-run your boot loader[grub]
The link /initrd.img is a damaged link
Removing symbolic link initrd.img 
 you may need to re-run your boot loader[grub]
Purging configuration files for linux-image-4.10.0-34-generic (4.10.0-34.38~16.04.1) ...
Examining /etc/kernel/postrm.d .
run-parts: executing /etc/kernel/postrm.d/initramfs-tools 4.10.0-34-generic /boot/vmlinuz-4.10.0-34-generic
run-parts: executing /etc/kernel/postrm.d/zz-update-grub 4.10.0-34-generic /boot/vmlinuz-4.10.0-34-generic
Reading package lists...
Building dependency tree...
Reading state information...
An error occured while a thread was running: 
             Type: <type 'exceptions.RuntimeError'>
Details: 
E: Unable to locate package default

**Comment by dlarue** [comment]
reverted to the 'stable' branch and it's working with this process:



sudo apt-get update && sudo apt-get install git
git clone https://github.com/kamilion/customizer
sudo apt-get install build-essential python-pip python-qt4-dev squashfs-tools xorriso x11-xserver-utils xserver-xephyr qemu pyqt4-dev-tools
sudo pip install pip-config

cd customizer
make && sudo make install
sudo customizer-gui

**Comment by dlarue** [comment]
If you're wanting to reproduce, an easy way to to make a bootable USB drive with a casper-rw(persistence) file or partition.  Another way is running the Lubuntu or Kubuntu(customizer 5.15 doesn't work) ISO in a virtual machine also with a casper-rw labeled partition and put "persistent" on the end of the boot line when grub shows the menu.

Stable, v 5.14 works.

**Comment by kamilion** [comment]
Hm, that's very strange, since I'm a lubuntu developer, most of the development occurs on lubuntu LTS.

I suspect you might be using someone else's build, as 4.1.5 hasn't even been released yet, so there shouldn't be a "5.14" version from me. I'm stumped.

As far as I know, your error isn't coming from Customizer.
"E: Unable to locate package default" is being returned from... apt? I think? Customizer's merely letting you know.

Personally, I start customizer from a terminal prompt so I can see what it's up to.

**Comment by dlarue** [comment]
I was installing from git / master and got the errors when it tried to build the ISO. I too run from commandline but it's a GUI app and I posted what the error was when it crashed.

My mistake, 4.14(stable) works and I tried 4.15(master branch) and got the errors.

**Comment by dlarue** [comment]
And maybe something changed as I used to be able to run Customizer from a LiveUSB Lubuntu environment.  Since getting this error, I've received and installed my new hard disk so I will try building Customizer master/4.15 from there and see if it runs.

**Comment by kamilion** [comment]
give `make PYTHON=python3 PYQT=5 deb` a shot to spit out a deb.

**Comment by dlarue** [comment]
will do.

**Comment by dlarue** [comment]
The building of the deb works and it appears to install.
I'm now downloading the iso of Lubuntu 16.04.3 to test it.

I only needed to add the qt4-linguist-tools package to my list of needed packages. See build process below:

sudo apt-get update && sudo apt-get install git
git clone https://github.com/kamilion/customizer
sudo apt-get install build-essential python-pip python-qt4-dev squashfs-tools xorriso x11-xserver-utils xserver-xephyr qemu pyqt4-dev-tools qt4-linguist-tools

cd customizer
make PYTHON=python3 PYQT=5 deb
sudo dpkg -i ../customizer_4.1.5-0+20170208_all.deb 
sudo customizer-gui

But it still fails when trying to build the ISO. Output from the commandline:

un-parts: executing /etc/kernel/postrm.d/zz-update-grub 4.10.0-28-generic /boot/vmlinuz-4.10.0-28-generic
Reading package lists...
Building dependency tree...
Reading state information...
An error occured while a thread was running: 
             Type: <class 'RuntimeError'>
Details: 
b'E: Unable to locate package default'

**Comment by kamilion** [comment]
Again, as far as I know, your error isn't directly coming from Customizer.
"E: Unable to locate package default" is being returned from apt.

my guess would be your /etc/customizer.conf needs to be regenerated, or I broke something with the kernel name parser, somewhere. ( https://github.com/kamilion/customizer/blob/972cd0f3890836b35e0c2d822841883838391d90/src/actions/rebuild.py#L147 )

Here's what the default config looks like when shipped:
https://github.com/kamilion/customizer/blob/master/data/customizer.conf#L20

And here's what a customized config looks like:
https://github.com/kamilion/kamikazi-core/blob/master/buildscripts/xenial/customizer-mini.conf

In this case, I'm using https://wiki.ubuntu.com/Kernel/LTSEnablementStack
`kernel = linux-signed-image-generic-hwe-16.04`
( https://packages.ubuntu.com/xenial/linux-signed-image-generic-hwe-16.04 )
to avoid getting the headers installed with the kernel.
`kernel = linux-generic-hwe-16.04`
( https://packages.ubuntu.com/xenial/linux-generic-hwe-16.04 )
Would include the headers too.

But normal people would probably want
`kernel = linux-image-generic`
( https://packages.ubuntu.com/xenial/linux-image-generic )
 or
`kernel = linux-signed-generic`
( https://packages.ubuntu.com/xenial/linux-signed-generic )

**Comment by dlarue** [comment]
I see what you are thinking, you're thinking that the error is from the ISO which is being burned?  Well, when I tested it I didn't customize anything, it's a stock Lubuntu image expanded by customizer and then attempted to be put back together.

I have Kubuntu 16.04.3 installed on my computer now and that errors out the same way.  I will try again, making sure the /etc/customizer.conf file is gone when I do the next test/installation of 4.15 but so far 4.14 has been working fine for me.

**Comment by kamilion** [comment]
I suspect it might have been a bug when running via python2.7

I'd suggest building with python3 and qt5 instead, then all the stupid unicode annoyances mostly evaporate.

(I don't think it's taking "default" as a unicode string in python2.7, I'll write some patches and try various things later to see if I can multiply the problem / make it worse, which should make it easier for me to diagnose.)

Sticking with the old version on python2.7's fine too.

**Comment by dlarue** [comment]
you found the location of the error. The kernel=default setting in the config file.

I built the deb package using python 3 and Qt5( after using pip to install PyQt5 ) and once I changed my config to linux-image-generic in the [saved] section it rebuilt an iso.

I will go back to trying python 2 and Qt4 since that doesn't give me a warning dialog on startup that I'm using Python 3.

**Comment by dlarue** [comment]
building with make PYTHON=pyton2 PYQT=4 deb worked too after the customizer.conf kernel was changed from "default".

But another error showed up in the python2 and qt4 build;  the clean button doesn't clean anything. I get the "confirm cleaning?" dialog and click OK but nothing happens.

In both builds(qt4/qt5) I did find that installing from deb does not install a default /etc/customizer.conf even though there appears to be on in the deb package( used dpkg -c to find ./etc/customizer.conf ).  So I've been copying from data/customizer.conf and only changed [saved] kernel= entry manually( besides GUI edits of workingDir and iso ).

**Comment by kamilion** [comment]
Messing around, trying to build a livecd while in a livecd, I ran into the problem myself; I'll take another look at what's going wrong with the code handling 'default'...

editing `kernel = linux-signed-generic` into /etc/customizer.conf fixed it.

**Comment by dlarue** [comment]
Yes, running from a live system is pretty amazing. Really fun getting things like Docker and things working by leveraging a partition on the thumb drive and sometimes using persistence.

I've been running with python3 perfectly using kernel=linux-image-generic

**Comment by KDStanhope** [comment]
Just to chime in and confirm that changing `kernel = linux-signed-generic` works.

**Comment by scuba156** [comment]
I just ran into this issue today

Changing this line
https://github.com/kamilion/customizer/blob/70fda48e9bb942b69cffd4d511f11911ddf0a3b2/src/actions/rebuild.py#L147
to this
```
if config.KERNEL != "default" or None:
``` 
fixes the issue and allows it to rebuild the ISO. I'm not familiar with python or your source but the type comparison shouldn't be needed.

**Comment by kamilion** [comment]
@scuba156 Please switch to building Customizer with Python3 and QT5.

`make PYTHON=python3 PYQT=5 deb`
or
`make PYTHON=python3 PYQT=5; sudo make install`

It's well known that python2 is quirky with a number of things -- this is one of them. The other one being unicode/bytes.

I'm pretty sure I changed that from != to is not during the py2 to py3 conversion.

Edit: Nope, I added that code using 'is not' initially. I'll try notequals in some compatibility tests, but since python2 isn't even on the ubuntu ISOs for 18.04, it's getting to be a moot point, and I'm probably just going to change the default to build with python3 shortly.

**Comment by scuba156** [comment]
I can't remember exactly as it was now a month ago, but I was in a particular situation where I had to build with the tools I had.

I was using this on a Mint 18.03 host to build a smaller Mint install ISO. Mint 18.03 only has python 2.7.12 I believe (checking my current install, this appears to be true).

On the machine I was using, the Mint Live ISO would not load the wifi drivers but would work fine after it was installed, so I could not update to python3 inside the Live ISO to build correctly, and the only way I could continue was by making the changes I noted above.

**Comment by kamilion** [comment]
@scuba156 Thanks for filling me in on the situation; that's helpful to know. I don't intend to stop supporting python2 for another year; but I'll probably invert the defaults soon, so one must ASK for python2 or QT4.

for reference, after the change, this would mean, in your situation, installation would be done with
`make PYTHON=python2 PYQT=4; sudo make install`

I'll also try a couple different things with 'is not' and != to see if py2/py3 treats it any different.

Customizer is exactly for things like you're using for, "oops, i needed the wifi package", so I'm glad it helped you out, in any case.

**Comment by suamor** [comment]
Just fyi, I'm using the version that is suggested by the starter tutorial (4.2.0-0-20180825), so master may be working. I'm having exact the same issue and can solve by replacing the default entry from the configuration. I'm using python3 + pyqt5 (which was default by me, so the tutorial is out of date in this regard, at least for 18.04.1). I'm on a Mate desktop (with Ubuntu as base).

**Comment by Mannshoch** [comment]
I have the same problem. I tried to get what was wrong and tried to mount some more linux devices.
`for dir in /dev /dev/pts /proc /sys /run; do sudo mount --bind $dir $PWD/$dir; done `
now the Error message changed.
![Bildschirmfoto von 2019-04-12 19-17-32](https://user-images.githubusercontent.com/7795891/56054683-bfa04380-5d57-11e9-8e12-0fa44bc55abb.png)
