### ISSUE TITLE
Make deb does not work, everything seems broken.

### ISSUE THREAD

**Issue by xamber123** [kamilion/customizer#189]
All dependencies according to first guide is installed. 
Running installer.py does not work. 
When running make deb command it fails almost instantly. 

Would paste if i could.

**Comment by kamilion** [comment]
Huh, sorry I didn't see this earlier; I'd need to know more details, like what distro, which spin, what version.

**Comment by xamber123** [comment]
It was some time ago but it was a debian jessie. I've also quit working at that specific company since then so i have no use for this anymore :P

**Comment by kamilion** [comment]
Alright, well, I've never tried to respin a debian ISO. Closing.
