### ISSUE TITLE
could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate'

### ISSUE THREAD

**Issue by Npizza** [kamilion/customizer#193]
Hi I am trying to install Qsynth but when I run sudo make install I get this error:
`make[2]: Leaving directory '/home/pizza/qsynth-0.5.0/src'
make[1]: Leaving directory '/home/pizza/qsynth-0.5.0'
lupdate: could not exec '/usr/lib/x86_64-linux-gnu/qt5/bin/lupdate': No such file or directory
Makefile:96: recipe for target 'translations_lupdate' failed
make: *** [translations_lupdate] Error 1`

I run linux mint

**Comment by kamilion** [comment]
I've never heard of QSynth before, sorry. This issue repository is for Customizer.
