### ISSUE TITLE
Error on rebuild Iso

### ISSUE THREAD

**Issue by Mannshoch** [kamilion/customizer#194]
Ubuntu 17.10
Source: Ubuntu 18.04 Image
Compile: make  PYQT=5 deb; sudo checkinstall

![grafik](https://user-images.githubusercontent.com/7795891/40225275-e3fe4fce-5a88-11e8-8d0b-02f2343fca50.png)

**Comment by suamor** [comment]
This should help you: https://github.com/kamilion/customizer/issues/184
I have the same issue. More or less this issue looks like a duplicate of the old one.

Workaround: Add a proper kernel package name to /etc/customizer.conf.

**Comment by Mannshoch** [comment]
thanks! that patch helped.

Now I have a new problem.
https://github.com/kamilion/customizer/issues/204

**Comment by paulocoghi** [comment]
@Mannshoch, don't forget to close this issue :)
