### ISSUE TITLE
Forked development status

### ISSUE THREAD

**Issue by clearkimura** [kamilion/customizer#2]
**I have created this issue to follow up progress of forked development, based on the decision I had made in [this comment of issue 70] of "old stable" repo.**

> **The decision**
> - As suggested by @kamilion this project repository remains as it is. No further migration.
> - The 'new' Wiki shall contain no duplicate pages and shall create its own pages; Only quote and link to 'old' Wiki when necessary i.e. FAQ page.
> - From now on, I consider the existing repository as "old stable" (as stated in the updated README.md and Wiki Home).

I just thought the progress should be followed up here, instead of dragging as "old stable" issue. I understand this will take some time, as we are leading different lives.

We may have further discussions here, should there be any difficulties to achieve what we had agreed back then; The only condition for no further migration: **Don't duplicate the Wiki**.

This issue shall remain open, as long as the condition is unfulfilled.

**Silent updates**

2016.03.26 -- Finished documentation clean up for Wiki in "old stable" repo; The Wiki will be reviewed for one last time by end of March 2016.

2016.03.30 -- Last review of Wiki in "old stable" may have finished. Allow one day buffer to see any feedback after announcing this in issue 70 of "old stable".

P.S.: Pull changes from "old stable" anytime after the review is done

2016.10.23 -- A copy of official fork was created as `forkout` branch in "old stable" (via [pull request 137]). This way, I could share non-duplicate fixes in "old stable" to official fork, if necessary.

[this comment of issue 70]: https://github.com/clearkimura/Customizer/issues/70#issuecomment-172900944
[pull request 137]: https://github.com/clearkimura/Customizer/pull/137

**Comment by clearkimura** [comment]
@kamilion 
You can now pull changes from "old stable" repo. I thought I should inform this before tomorrow arrives (I won't be replying anything on 1 April).

As for the forked Wiki, pulling changes from "old stable" is agreed for your convenience to follow any useful formatting. However, as per the only condition, the content must be entirely new. If old content is still useful, consider linking back instead. For example: "Refer to [FIrst guide on old stable Wiki](https://github.com/clearkimura/Customizer/wiki/First-guide)".

From a user point of view, I see the most important pages are **Home** and **FAQ**. The other remaining pages should be deleted in forked Wiki. This will simplify things and save time to commit to create contents on Wiki.

For any follow up, I will reply from 2 April (UTC) onwards.

**Comment by kamilion** [comment]
Alright, will poll branch 'forkout' for updates the next time I roll through github.

**Comment by clearkimura** [comment]
@kamilion 
Um... I didn't mean to update fork itself.

The `forkout` branch is supposed to "follow and up to date" with the official fork and not the opposite; despite GitHub repositories are being bidirectional. It was meant to bring compatible updates forward from "old stable" to fork, and only when necessary.

The fork just had its "forward fix" for first time. That is, after 3 months of activity in "old stable". And those fixes are trivial and mostly due to clean up and to be consistent.

When there is any compatible update to be shared with fork, I will create new pull request and you will be notified automatically for that.

So, there's no reason to do extra job to poll the branch regularly.

**Comment by clearkimura** [comment]
@kamilion 
I am now very confused. What is the development plan of official fork? I don't understand why is the fork `master` becomes even with "old stable"? This will seriously confuses end users, because most of the changes in "old stable" is *not* meant to be applied to fork.

**Comment by clearkimura** [comment]
This issue shall be closed, since "old stable" will be deprecated. The only condition for no further migration (don't duplicate the wiki), is no longer relevant. Case solved.
