### ISSUE TITLE
ISSUE SUBMISSION GUIDE

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#50]
To report issues, click `New Issue` button. You will have to log into your account at GitHub or create a new account. Then, write your issue in detail.
#### For End users

User should write at least something like this:

```
 Running Customizer 3.2.1 PPA on Ubuntu 12.04 32-bit host.
 Selected ubuntu-mini-remix-12.04-amd64.iso, after select 'Build',
   cannot create ISO image file, Terminal shows output error like this:
 “Error 119: No kernel found when compiling image”.
```

Remember to provide as much as possible information. Those will be the clues on how we can solve the issue. User can include other information, such as:
-  **Screenshots** --- User can easily upload single or multiple images within the same text area, when submitting issue via GitHub. Else, include permalink to cloud storage location (if any).
-  **Log files** --- Run Customizer from Terminal, `Select All` output that appear in Terminal, then copy-paste the output to [Pastebin.com](http://pastebin.com/). Else, include permalink to cloud storage location (if any).
-  **Step-by-step instruction** --- Tell us how to reproduce the issue from start until end. Recommended for users who can recall everything.

Note that only issues found in latest release of Customizer are concerned (User can see the latest version announced at [Customizer Wiki page](https://github.com/fluxer/Customizer/wiki) on GitHub). Issues in older versions will be ignored.
#### For Development Team

Here is how to identify the issues which are registered by Customizer Development Team, also known as official issues. The following format (standardized in user guide since 2012) shall be used:

```
 ISSUE-YYYY-NNN (OPTIONAL TITLE)
 in which,
    YYYY is a four-digit year
    NNN is a three-digit issue number registered for that year
and
    OPTIONAL TITLE is the short description for the issue, to be readable.
```

For example, in user guide, there are six issues identified in 2011, so the registered issue numbers are ISSUE-2011-001 .. ISSUE-2011-006. But since no new issues being identified in 2012, following issues found are named as ISSUE-2013-001, and -002. 

Hence, official issues submission for this year shall be ISSUE-2014-001, -002 and so forth.
##### What are official issues

To this date, the "official issues" refer to issues that have been identified by Customizer development team. The following criteria applies:
1.  The issue still affects latest release of Customizer
2.  The environment and/or factors that can reproduce the issue are well known
3.  Based on criterion no.2, Customizer Development team is able to reproduce the issue

As such, typical issue submission by end users may not be registered as "official submission", unless satisifies all three conditions above.
##### The content of official issues
-  **Issue name** -- follow format as explained above
-  **Summary** -- short description of issue
-  **Environment** -- operating system, applications affected
-  **Description** -- long description of issue
-  **Workaround** -- temporal cure or clever tricks with limitations, but doesn't solve the issue
-  **Solution** -- permanent cure that solves the issue
##### How to manage resolved issues?

Previously, the user guide has been updated to remove resolved issues. This may explain why ISSUE-2012-001, etc. went missing in most recent user guide.

In contrast, when these issues are moved to GitHub and later resolved, these official issues will _not_ be removed but only marked as "Closed". This is useful--whenever the issue was later found as unresolved, someone can reopen to rectify the issue again.

Last updated: 2014-11-12

**Comment by hreikin** [comment]
@clearkimura I will make this a sticky topic in the forums issue section

**Comment by ghost** [comment]
@hreikin 
I have also added a link to this issue on GitHub Wiki page. This issue may be revised from time to time, so I have added "Last updated" date in the last line of the post above.

**Comment by hreikin** [comment]
work on the forum will start in 3 hours, should have it finished by tomorrow before work.

@clearkimura @fluxer when the forum is up and running I will make both of you moderators

**Comment by fluxer** [comment]
@hreikin Ok.

**Comment by hreikin** [comment]
http://customizer.freeforums.org/

@fluxer @clearkimura please create an account and i will make you mods

i am having issues posting the issues lol, i think its the markdown and bbcode not playing nicely but dont know for certain, for the moment the issue posts are just links, i will do a general overview of the issue in the post

**Comment by ghost** [comment]
@hreikin 
I have registered at your request. I may be offline most of time, but I will try to check the forum every week or two. The good thing about this forum is, it has mobile view!

**Comment by fluxer** [comment]
@hreikin Just registered with nickname smil3y, thank you for your contribution!

**Comment by hreikin** [comment]
@clearkimura i noticed this too, haven't tried out the admin control panel yet on my phone tho

@fluxer thanks i will make you both mods now

the forum is still in construction, i will try finish it by tomorrow or i will keep working on it after work all week

**Comment by mitsuzero** [comment]
El 07/02/2014 01:05, "mic" notifications@github.com escribió:
V, should have it finished by tomorrow before work.

**Comment by ghost** [comment]
This guide will be revised to much simple instructions and soon to be replaced by [this new page](https://github.com/clearkimura/Customizer/wiki/Issue-submission). The new page should be accessible from any Wiki page via Sidebar. In progress.

**Comment by ghost** [comment]
The new [Issue submission](https://github.com/clearkimura/Customizer/wiki/Issue-submission) page has been mostly updated, therefore this issue will be closed.
