### ISSUE TITLE
ISSUE-2011-004 (Unable to login into created ISO Live image)

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#54]
Unable to login into the created Live CD/DVD ISO image
##### Environment

Customizer 3.2 and newer releases, regardless of the environment.

Known application with this issue:
- Dropbox 1.6
##### Description

There are some limitations in matter of what signs should be used for the live username, I can't say which exactly may cause issues but avoiding any special characters like  `,.<>|%^&*()`  etc. should solve this problem. Also make sure to use US keyboard layout to enter that.

In related case, at least one user has attempted to install Dropbox using their official **.deb** file in chroot environment. This has also caused the rebuild ISO unable to login when boot as Live CD.
##### Workaround

None
##### Solution

Change the Live CD username to something simple, for example, "live" (without the quotes) and try to rebuild the ISO again.

Don't install Dropbox in chroot environment.

Last updated: 2014-02-08

**Comment by nvgringo** [comment]
Hello, I attempted to remaster the 64 bit version of Ubuntu Mate 14.04. I started with a blank hard drive and installed the version that I wanted to remaster. The host system requires a password to log in. I installed the dependencies then I installed Customizer. and opened the ISO.  I was able to open the desktop of the remaster and added a few plug ins in Firefox. Without making any other changes I created the new ISO. When I Qemu into the new ISO I am prompted for a password. I have tried the host name as the user name with the password blank. I have tried ubuntu with the password blank. I have tried the username and password of the host system. No luck. I have not used or installed dropbox. I have wiped the hard drive and started over with the same results.

**Comment by ghost** [comment]
@nvgringo 
I assume you are using Customizer 4.1.0 from **master** branch, running on 64-bit host system, and using 64-bit ISO image file. Also, can you clarify again by following steps below?
1. In Customizer, **Select ISO** image file (in your case, Ubuntu Mate 14.04 64-bit ISO)
2. After fully extracted ISO, do nothing. Directly proceed to **Rebuild ISO**.
3. Finally, try the newly created ISO from **QEMU**.

Now does the live CD able to login automatically?

**Comment by nvgringo** [comment]
Sorry, your email went into my spam folder. 
I installed the dependancies 
I downloaded Customizer using wget (as instructed)the deb build failed.There is a program called git that was not found. I installed git using apt-get and the build worked. I ran customizer from the menu.
I extracted the iso and rebuilt the iso without making any changes.I installed a game Chromium-bsu using the terminal option.There was an error when I closed the terminal using the exit command.
I rebuilt the iso and started it through QEMU.It opened and the game was installed.I then closed and restarted Customizer. I opened the Desktop. It started fin and the desktop was visible. I made no changes. I received the error (photo attached) when I closed the desktop.I rebuilt the iso.the next time I opened the iso with QEMU the password promp was there

@nvgringo 
I assume you are using Customizer 4.1.0 from master branch, running on 64-bit host system, and using 64-bit ISO image file. Also, can you clarify again by following steps below?   
- In Customizer, Select ISO image file (in your case, Ubuntu Mate 14.04 64-bit ISO)
- After fully extracted ISO, do nothing. Directly proceed to Rebuild ISO.
- Finally, try the newly created ISO from QEMU.
  Now does the live CD able to login automatically?—

**Comment by ghost** [comment]
@nvgringo 
Added comments as below.

> I downloaded Customizer using wget (as instructed)the deb build failed.There is a program called git that was not found. I installed git using apt-get and the build worked. 

Which instruction? The recommended [install method in the first guide](https://github.com/clearkimura/Customizer/wiki/First-guide#4-how-to-install-customizer) doesn't require `git` at all.

>  I ran customizer from the menu. I extracted the iso and rebuilt the iso without making any changes.

So.. can I assume you managed to login to Live CD at this stage? If did manage, that means most likely this issue was caused by package that is installed to Live CD, not Customizer fault.

> There was an error when I closed the terminal using the exit command.

The error was seen while using Customizer in Terminal only? I have never seen one before. Can you please include the output from Terminal or screenshot?

>  I received the error (photo attached) when I closed the desktop

No, there isn't any photo when viewing on GitHub here. You should attach image when replying from GitHub and _not_ attach image in E-mail.

> the next time I opened the iso with QEMU the password promp was there

So, not only Firefox plugin, but other package i.e. Chromium-bsu also causing this issue? Can you include the output from the Terminal?

P.S.: Read [this guideline](https://github.com/clearkimura/Customizer/wiki/Issue-submission#3-explain-the-issue) to see the output from the Terminal.

**Comment by nvgringo** [comment]
```
I downloaded Customizer using wget (as instructed)the deb build failed.There is a program called git that was not found. I installed git using apt-get and the build worked.
```

Which instruction? The recommended install method in the first guide doesn't require git at all.
This time I used the "First Guide" step by step but when I ran
sudo dpkg -i *.deb the build failed. I looked the termal output and found this section
removed ‘debian/customizer.debhelper.log’
/bin/sh: 1: git: not found
sed -e 's|@VERSION@|4.1.0 (stable)|' -e 's|@PREFIX@|/usr|g' \
        src/main.py.in > src/main.py
/bin/sh: 1: git: not found
sed -e 's|@PREFIX@|/usr|' -e 's|@ELEVATOR@|pkexec|' \
        data/customizer.menu.in > data/customizer.menu
sed -e 's|@PREFIX@|/usr|' -e 's|@ELEVATOR@|pkexec|' \
        data/customizer.desktop.in > data/customizer.desktop
sed 's|@PREFIX@|/usr|' data/customizer.policy.in > \
        data/customizer.policy
sed -e 's|@VERSION@|4.1.0 (stable)|' -e 's|@PREFIX@|/usr|g' \
        src/gui.py.in > src/gui.py
I saw two instances of "/bin/sh: 1: git: not found" so I thought what harm in apt-get install git. After I did so. the program installed without further issue

```
I ran customizer from the menu. I extracted the iso and rebuilt the iso without making any changes.
```

So.. can I assume you managed to login to Live CD at this stage? If did manage, that means most likely this issue was caused by package that is installed to Live CD, not Customizer fault.

It is correct that I could build an image that boots as long as I do not make a single change. But I am not sure that I agree that the problem is a package that I installed. I will try to explain in the points below.

```
There was an error when I closed the terminal using the exit command.
```

The error was seen while using Customizer in Terminal only? I have never seen one before. Can you please include the output from Terminal or screenshot? 
The window title is: Critical(as superuser)
The error message is: Command '('/user/bin/mate-terminal', '-e', 'customizer -D -c')' returned non-zero exit status 255
I think this is a known issue

```
I received the error (photo attached) when I closed the desktop
```

No, there isn't any photo when viewing on GitHub here. You should attach image when replying from GitHub and not attach image in E-mail.
I will try

So, not only Firefox plugin, but other package i.e. Chromium-bsu also causing this issue? Can you include the output from the Terminal?

No the game installed fine because I installed it through the terminal without opening Xephyr. Once I open Xephyr I will get an error. When I close Xepher, even if I change nothing at all. Just look at the default desktop.
 and the next time I open QEMU it will promp for a password.

**Comment by nvgringo** [comment]
no way to attach photos.
Here is the error when Xephyr exits(after only viewing the default desktop):
mate-session[3407]: WARNING: Unable to determine session: Unable to lookup session information for process '3407'

*\* (mate-settings-daemon:3424): WARNING **: Failed to connect context: OK

*\* (polkit-mate-authentication-agent-1:3470): WARNING **: Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Connection failure: Connection refused
pa_context_connect() failed: Connection refused

*\* (update-notifier:3471): WARNING *_: not starting for system user
*_ Message: Initializing gksu extension...
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
The application 'mate-session' lost its connection to the display :13;
most likely the X server was shut down or you killed/destroyed
the application.
mate-settings-daemon: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.
Window manager warning: Fatal IO error 11 (Resource temporarily unavailable) on display ':13'.
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
mate-panel: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.
caja: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.

(deja-dup-monitor:3476): GVFS-RemoteVolumeMonitor-WARNING **: Owner of volume monitor org.gtk.Private.UDisks2VolumeMonitor disconnected from the bus; removing drives/volumes/mounts
g_dbus_connection_real_closed: Remote peer vanished with error: Underlying GIOStream returned 0 bytes on an async read (g-io-error-quark, 0). Exiting.
mate-screensaver: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.
blueman-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.

(nm-applet:3521): Gdk-WARNING **: nm-applet: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.

mate-power-manager: Fatal IO error 11 (Resource temporarily unavailable) on X server :13.

**Comment by nvgringo** [comment]
This is the output from the terminal:
 Starting nested X session: mate-session
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/Type1, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
[1429220788,000,xklavier.c:xkl_engine_start_listen/]    The backend does not require manual layout management - but it is provided by the application
GNOME_KEYRING_CONTROL=/etc/skel/.cache/keyring-sw8tTf
SSH_AUTH_SOCK=/etc/skel/.cache/keyring-sw8tTf/ssh
GPG_AGENT_INFO=/etc/skel/.cache/keyring-sw8tTf/gpg:0:1
GNOME_KEYRING_CONTROL=/etc/skel/.cache/keyring-sw8tTf
SSH_AUTH_SOCK=/etc/skel/.cache/keyring-sw8tTf/ssh
GPG_AGENT_INFO=/etc/skel/.cache/keyring-sw8tTf/gpg:0:1
GNOME_KEYRING_CONTROL=/etc/skel/.cache/keyring-sw8tTf
SSH_AUTH_SOCK=/etc/skel/.cache/keyring-sw8tTf/ssh
GPG_AGENT_INFO=/etc/skel/.cache/keyring-sw8tTf/gpg:0:1
GNOME_KEYRING_CONTROL=/etc/skel/.cache/keyring-sw8tTf
SSH_AUTH_SOCK=/etc/skel/.cache/keyring-sw8tTf/ssh
GPG_AGENT_INFO=/etc/skel/.cache/keyring-sw8tTf/gpg:0:1
Loading configuration plugins
blueman-applet version 1.23 starting
Stale PID, overwriting
Initializing caja-open-terminal extension
Initializing caja-main-menu extension
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
Using file config backend
  => Terminating Xephyr

**Comment by ghost** [comment]
@nvgringo 
Added more comments:

> I saw two instances of "/bin/sh: 1: git: not found" so I thought what harm in apt-get install git. After I did so. the program installed without further issue

So I had been missing/ignoring those messages until now. Probably `git` is used to verify files between local and GitHub repo, but I find nothing major.

In fact, I have been installing Customizer with the existing method, I can install normally even the errors were seen as above. I will check again and will update the first guide if needed.

> The window title is: Critical(as superuser)
> The error message is: Command '('/user/bin/mate-terminal', '-e', 'customizer -D -c')' returned > non-zero exit status 255
> I think this is a known issue

True, issue #90 which I had filed.

> no way to attach photos.

GitHub has [this](https://help.github.com/articles/issue-attachments/) feature [since late 2012](https://github.com/blog/1347-issue-attachments). You must have missed that.

>  Here is the error when Xephyr exits(after only viewing the default desktop):

I am _not_ a developer so the errors you are seeing are almost meaningless to me and you, being end-users. While working on my remix in previous years, I have seen similar errors all the while but most of the time I do nothing with it.

And no, since those debug messages are generated by Xephyr or the chroot system of the ISO you are remastering, these are _not_ much relevant for troubleshooting Customizer issues (at least to me).

> No the game installed fine because I installed it through the terminal without opening Xephyr. Once I open Xephyr I will get an error. When I close Xepher, even if I change nothing at all. Just look at the default desktop. and the next time I open QEMU it will promp for a password.

In this case, I just needed this information to find the cause that triggered this issue. So now I estimate this issue will occur when **Desktop** feature is used before rebuilding ISO?

**Comment by nvgringo** [comment]
Yes, I think it is when the Desktop feature is used. I did not realize that you were an end user as well. Thanks for maintaining the program I have used it in the past and really like Customizer. There are a couple of items in the Dialog message and in the terminal that I may try to research
"...Unable to register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject
Cannot register authentication agent: GDBus.Error:org.freedesktop.PolicyKit1.Error.Failed: An authentication agent already exists for the given subject..."
And "...GNOME_KEYRING_CONTROL=/etc/skel/.cache/keyring-sw8tTf..."
 I will let you know if I can figure anything out. If you have any ideas please let me know. 
Aslo it is worth mentioning that I have the same problem with the 32 bit version

**Comment by ghost** [comment]
@nvgringo 
Comments as below.

> Yes, I think it is when the Desktop feature is used.
> [...]
> Aslo it is worth mentioning that I have the same problem with the 32 bit version

Did you mean, when remastering Ubuntu MATE 32-bit ISO on 32-bit host system? I have some doubts but I can't say for sure, unless there is any proof.

Have you tried with other ISO images? Because as far as I had experienced recently, at least official ISO image for Xubuntu 14.04 doesn't suffer from this issue.

> There are a couple of items in the Dialog message and in the terminal that I may try to research...

When doing anything in chroot environment, there have been always limitations such as unable to run D-Bus-related processes, some applications and tiny applet such as network manager (I experienced this in both Ubuntu and Xubuntu).

Not surprising for me, since I had been into remastering process with these limitations. It didn't bother me much, as long as most of the settings can be tweaked to some extent.

> Thanks for maintaining the program I have used it in the past and really like Customizer.

Just doing what I can--mainly documentation and occasional testing.

I have used since version 3.2.x. You said that "have used Customizer in the past" but since when/which version? Have you tried with other remastering tools such as UCK, etc?

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.

For future issues, please submit to official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
