### ISSUE TITLE
customizer 3.2.3 *buntu 14.04 apt-get/tasksel/aptitude upgrade fails to configure modemmanager and whoopsie

### ISSUE THREAD

**Issue by magowiz** [kamilion/customizer#66]
I noticed this on each try I did using various ISO (ubuntu, xubuntu, ubuntu mini remix) all of them 14.04 . If I choose to upgrade the packages to last versions I get an error on configure libpam that comes out every time I install a new package or upgrade existing one :   

dpkg: error processing package modemmanager (--configure):
 subprocess installed post-installation script returned error exit status 100
Setting up whoopsie (0.2.24.5) ...
invoke-rc.d: unknown initscript, /etc/init.d/whoopsie not found.
dpkg: error processing package whoopsie (--configure):
 subprocess installed post-installation script returned error exit status 100
Errors were encountered while processing:
 modemmanager
 whoopsie

**Comment by magowiz** [comment]
I integrate previous error message :  
Setting up modemmanager (1.0.0-2ubuntu1) ...
invoke-rc.d: unknown initscript, /etc/init.d/modemmanager not found.
dpkg: error processing package modemmanager (--configure):
 subprocess installed post-installation script returned error exit status 100
Setting up whoopsie (0.2.24.5) ...
invoke-rc.d: unknown initscript, /etc/init.d/whoopsie not found.
dpkg: error processing package whoopsie (--configure):
 subprocess installed post-installation script returned error exit status 100
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by magowiz** [comment]
Touching /etc/init.d/modemmanager and /etc/init.d/whoopsie creating empty files is a workaround for this issue

**Comment by blinskey** [comment]
The same issue and workaround exist for vsftpd on 14.04: running `touch /etc/init.d/vsftpd` before installing the package prevents the error.

**Comment by fluxer** [comment]
Similar reports have been made in issue #63.

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.

For future issues, please submit to official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
