### ISSUE TITLE
Customizer 3.2.3 : *buntu 14.04 rebuilt iso cannot shutdown properly

### ISSUE THREAD

**Issue by magowiz** [kamilion/customizer#69]
Running Customizer 3.2.3 gambas3 branch installed via install.sh script on Ubuntu 14.04 64-bit host.
 Selected ubuntu-mini-remix-14.04-amd64.iso and xubuntu-14.04-amd64.iso, after selected the iso, I only set up properly proxy into apt.conf file, then rebuilt the iso as it is, the rebuilt iso boots fine under virtualbox but it fails to shutdown properly : 
it doesn't show the "remove disk and press enter to shutdown" message I get from original xubuntu, and it hangs/wait endlessly, right after the Deactivating Swap phase and it doesn't perform hardware shutdown.

**Comment by hreikin** [comment]
@magowiz have you tried just removing the disk and pressing enter like normal ? i have had a similar problem before while using another liveCD customisation tool, where i thought it was hanging when in fact it was waiting for me to remove disk and press enter before it carried on with the shutdown

**Comment by ghost** [comment]
@magowiz 
After I confirmed the support for 14.04 release (issue #61), I had tried to boot my test remix (minimal Xfce4 Desktop Environment) and shutdown from VirtualBox emulator.

The shutdown message was normal in my case; the message "remove disk and press enter to shutdown" can be seen. When I press Enter key, the VirtualBox window immediately closes and no waiting issue as you had experienced.

If you are rebuilding from Ubuntu Mini Remix, make sure you have installed sufficient packages to handle the session properly.

What I mean by "sufficient packages" is, such as login manager (gdm, lightdm or such) and xfce4-utils (or libxfce4ui-utils) package for xfce4 DE on 12.04 (or 14.04 release) which are closely responsible for proper session handling.

If there is any other difference, that would be different CPU architecture. I am using 32-bit for both host system and ISO image file. On the other hand, you are using 64-bit. Sometimes, 64-bit has issues which 32-bit doesn't experience.

Kindly confirm that this issue is not due to above reasons.

**Comment by ghost** [comment]
This issue is over a month old. Since there is no feedback until now, I will close this issue until someone can reproduce and reopen this issue.

**Comment by fluxer** [comment]
Indeed, but it is valid for 14.04 and 4.1.0 which is important the way I see it.
Can we have this open so the issue is not out of the focus of feature
reporters to avoid dublicate and hopefully someone can try to figure it out?

**Comment by ghost** [comment]
While looking into separate issue #75 , I could tell that this "cannot shutdown properly" issue didn't happen with rebuilded UMR 14.04 ISO 32-bit with Customizer 4.1.0 on 14.04 32-bit host system.

Live session running in VirtualBox did show the message "remove disk and press enter to shutdown" during shut down process.

Although, I have only confirmed in CLI environment only.

**Comment by carlossoy** [comment]
Hi good morning.
Sorry I can not explain it better but not English and I use google translator.
I keep getting the same problem with libpam-systemd package.

When you upgrade package gives me this error: E: /var/cache/apt/archives/libpam-systemd_204-5ubuntu20.11_amd64.deb: subprocess new pre-removal script returned error exit status 100

This is the complete process of synaptic:
(Synaptic: 5972): GLib-CRITICAL **: g_child_watch_add_full: assertion 'pid> 0' failed
(Reading database ... 325215 files and directories Currently installed.)
Preparing to unpack ... / libpam-systemd_204-5ubuntu20.11_amd64.deb ...
invoke-rc.d: initscript unknown, /etc/init.d/systemd-logind not found.
dpkg: warning: subprocess pre-removal script old returned error exit status 100
dpkg: trying script from the new package Instead ...
invoke-rc.d: initscript unknown, /etc/init.d/systemd-logind not found.
dpkg: error processing /var/cache/apt/archives/libpam-systemd_204-5ubuntu20.11_amd64.deb archive (--unpack): subprocess new pre-removal script returned error exit status 100
/ Bin / df '/ media / DATA': No such file or directory / bin / df '/ sys / fs / cgroup / systemd': No such file or directory invoke-rc.d: initscript unknown, / etc / init.d / systemd-logind not found.
dpkg: error while cleaning up: subprocess installed post-installation script returned error exit status 100
Preparing to unpack ... / systemd-services_204-5ubuntu20.11_amd64.deb ...
Unpacking systemd-services (204-5ubuntu20.11) over (204-5ubuntu20.7) ...
Preparing to unpack ... / libsystemd-daemon0_204-5ubuntu20.11_amd64.deb ...
Unpacking libsystemd-daemon0: amd64 (204-5ubuntu20.11) over (204-5ubuntu20.7) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Errors Were Encountered while processing: /var/cache/apt/archives/libpam-systemd_204-5ubuntu20.11_amd64.deb
E: Sub-process / usr / bin / dpkg returned an error code (1)
A package failed to install. Trying to recover:
Setting up libsystemd-daemon0: amd64 (204-5ubuntu20.11) ...
dpkg: dependency problems Prevent configuration of libpam-systemd: amd64: libpam-systemd: amd64 depends on systemd-services (= 204-5ubuntu20.7); however it: Version of systemd-services on system is 204-5ubuntu20.11.
dpkg: error processing package libpam-systemd: amd64 (--configure): dependency problems - leaving unconfigured
Setting up systemd-services (204-5ubuntu20.11) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
Errors Were Encountered while processing: libpam-systemd: amd64

My operating system is Ubuntu 14.04 amd 64 and the operating system is the same attempt customize 14.04 amd 64

The problem exists only in the customization process, in my pc there is no such problem, the package has been updated.

Hope this serves to improve your program.
A Greeting. Carlos from Spain

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.

For future issues, please submit to official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
