### ISSUE TITLE
New maintainers for Customizer

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#70]
**Revised on 2016.08.23**

Should anyone wish to manage Customizer development on GitHub (become the repo owner and/or main developer), simply [leave a comment at below](#new_comment_field). Else, contact [development team in the list](https://raw.githubusercontent.com/clearkimura/Customizer/master/Contributors) and current repo owner via `clearkimura@gmail.com` regarding repo transfer or project transition.

**Repository status**

The current repo owner @clearkimura will no longer be active from 31 December 2015. Although, he may still be found doing documentation clean up on GitHub Wiki and Issues. Following this, he will be "not watching" this repository (effective from 30 March 2016).

> Not watching: Be notified when participating or @mentioned.

This existing repository is now considered as "old stable". Since January 2016, there has been no [changes to master branch](https://github.com/clearkimura/Customizer/commits/master) except for updating `README.md` and other files related to documentation.

**Background story**

The development of Customizer had stopped about one year ago from this date (Jul 29, 2014). The original developer did backport some codes in late 2013, which eventually became **devel** branch.

Back then, the original developer @fluxer had transferred the GitHub repo to the documentation contributor @clearkimura with hope that at least someone can continue to look after repo, even when the original developer is not around.

Between late-2014 and early-2015, codes have rewritten in Python and changes were merged into **master** branch. With the help of few recent contributors, Customizer has now better support for 15.04 and newer releases and requires significantly less memory to rebuild ISO image.

The current repo owner has been a documentation contributor, and very far from being a developer. The most significant effort was giving useful feedback as tester, which is only possible, while being a user of Ubuntu or its derivative. The continual feedback is provided for LTS releases, since 10.04.

The feedback, however, will no longer be possible since the current repo owner has lost interest in remastering Ubuntu-based remix newer than 14.04 release. One reason is, because of many major changes happening within Ubuntu development (such as systemd).

Testing Customizer will be meaningless, since the current repo owner may not be using Ubuntu or its derivative anymore after 14.04 release (worst case scenario after trying out the next LTS release, 16.04). Therefore, any useful feedback and even documentation is almost impossible.

**Summary**

New maintainers are needed to continue development and adapt to changes being made to Ubuntu in future releases. That means, Customizer is better maintained in the hands of active contributors.

**Comment by fluxer** [comment]
I've been working on the devel branch, since I have free time now and been playing with Xubuntu, to make it work with recent Ubuntu release and improve it where possible. As far as I can tell it works fine with Xubuntu and Ubuntu Mini Remix, there are only two things to be worked on (as far as the core goes):
1. filesystem manifests
2. qemu

I will try to implement those the right way and I think this will be as far as I go. Maybe a few commits every now and then but nothing major.

**Comment by ghost** [comment]
@fluxer 
Hi, glad to hear from you again! Some things to clarify with you:

> As far as I can tell it works fine with Xubuntu and Ubuntu Mini Remix

Did you mean Xubuntu 14.04 only, or all currently supported releases (including 12.04)?
And I assume you mean works fine with the devel branch only.

Because I have tested the official Xubuntu 14.04 ISO with Customizer gambas3 branch and it cannot boot after rebuild (you may know this already, discussed under issue #61 in past weeks).

But at least gambas3 branch still can handle Ubuntu Mini Remix 14.04 ISO properly. So this is still considered supported.

> I've been working on the devel branch

I wanted to try out the devel branch, but install.sh script cannot install devel branch properly. I submitted separate issue #72 just now for short discussion (Geez, I had forgotten about README).

**Comment by fluxer** [comment]
@clearkimura 
Hi,

> Did you mean Xubuntu 14.04 only, or all currently supported releases (including 12.04)?
> And I assume you mean works fine with the devel branch only.

I've tested Xubuntu and UMR ISOs 13.04, 13.10 and 14.04 - all i386 architecture. And yes, they work fine with the devel branch as this is what I've been working on and testing.

> Because I have tested the official Xubuntu 14.04 ISO with Customizer gambas3 branch and it cannot boot after rebuild (you may know this already, discussed under issue #61 in past weeks).

I've done many rebuilds and most of them were successful, except those in which the kernel has been updated but a control file (I suspect .disk/casper-uuid-generic in the ISO root) has not. I have no idea how it is generated yet - random or from some static data. I found this recently but it is not critical for now as usually the kernel is held back automatically by `apt-get`. even on upgrade.

> But at least gambas3 branch still can handle Ubuntu Mini Remix 14.04 ISO properly. So this is still considered supported.

I guess, but even so is not going to work well with the newest releases - they have a few differences (manifests, meta information stored on the ISO and more) so the end product will not be stable/bug free (bugs like the boot problem).

> But at least gambas3 branch still can handle Ubuntu Mini Remix 14.04 ISO properly. So this is still considered supported.

Problem is that UMR is not a good choice anymore - its maintainer is using some old scripts to build it probably. For an example memory test and disk consistency check does not work on UMR. I know why but I'm not going to report that, instead I've fetched Xubuntu and Ubuntu ISOs to use and test on. That's the reasons it still (kind of) works but do not recommend its new releases anymore (starting from 12.10+).

> I wanted to try out the devel branch, but install.sh script cannot install devel branch properly. I submitted separate issue #72 just now for short discussion (Geez, I had forgotten about README).

I've figured something better for installation - devs can install it manually (very easy, follow the instructions in the README) and deb package for the end users. The devel branch tree includes debian directory where package files are stored, it is generic for now but I read it can have sub-directories for different releases (e.g. jessie, trusty, etc.). Building deb package is as easy as typing `make deb` in the top directory of the Git tree (on devel branch) assuming you have at least build-essentials, python-dev v2.7, python-qt4 and pyqt4-dev-tools, qt4 dependencies can be avoided as you can build only the core/CLI but it is not so by default. Ofcourse our PPA maintainer can probably setup something on Launchpad but for now if I want someone to test it I can build and send him deb package if he is running Debian/Ubuntu.

I hope I explained well, cheers!

**Comment by ghost** [comment]
@fluxer 
Thanks for your support!

>  python-dev v2.7, python-qt4 and pyqt4-dev-tools, qt4 dependencies can be avoided as you can build only the core/CLI..

Oh, that explained a lot. Though, I learned about the dependencies by hard way..

>  ..but it is not so by default.

Um, which means you didn't include these qt4 dependencies on purpose?
I just updated dependencies to README.md on devel branch.. (slap on forehead).

**Comment by fluxer** [comment]
@clearkimura 

> Oh, that explained a lot. Though, I learned about the dependencies by hard way..

Sorry, Debian/Ubuntu have their own way. Usually python-dev is part of python, pyqt4-dev-tools is part of pyqt4. I was trying to be generic in the README not ubuntu specific. I will make a minor correction on top of your edit.

> Um, which means you didn't include these qt4 dependencies on purpose?

I haven't checked if the package names are the same across different Ubuntu releases so I didn't wanted to provide some incomplete information but it's ok.

**Comment by kamilion** [comment]
I guess I'll start maintaining from https://github.com/kamilion/customizer then, since it looks like I'm one of the few remaining users. I cloned the wiki repo and copied it over as well, added this repo as the upstream. I think the only thing I can't copy is the issues/PRs.

**Comment by fluxer** [comment]
@kamilion That's not the only option. 1) the repository can be transferred to you and you become administrator of it, 2) you can be added to the list of collaborator, 3) you just submit pull requests and edit the wiki at will without 1) or 2) or 4 you fork off, the reference to the original repository is kept in your fork page and you can reference issues, commits, etc. in your own commits and issues.

Whatever you choose it will be the same after all.

**Comment by kamilion** [comment]
Considering a lot of the repo has history dating back to the gambas days, this might be a good time to make a clean break over to the new python setup, as I don't really intend on ever touching the gambas branch, personally.

The other issue is, I'm sort of expecting canonical to drop python 2.7 on the livecd in either 16.04 or 16.10, so there's kind of a need to move towards python 3 and qt5.

**Comment by kamilion** [comment]
That's assuming @clearkimura feels like keeping the old repo around and in a zombie state; perhaps setting a gmail filter to mark them read...

I've already set up a local customizer repo on my 16.04 buildbox, spinning lubuntu ISOs from it every few weeks as xenial progresses. @clearkimura is the remote named 'upstream' for now.

We'll see what gets decided on in the coming weeks.

**Comment by ghost** [comment]
@kamilion @fluxer 
Sorry for delayed notice. I need to ask for clarification on what have been decided by you guys. My replies follow after the quoted text.

> I cloned the wiki repo and copied it over as well, added this repo as the upstream. I think the only thing I can't copy is the issues/PRs.

But I thought I ought to transfer this repo to the new maintainer as what @fluxer suggested? This will also solves the issue of copying issues/pull requests, isn't?

> [...] this might be a good time to make a clean break over to the new python setup, as I don't really intend on ever touching the gambas branch, personally.

Even after the repo transfer, development only takes place in master branch (or newly created branch, if any). So why would "touching the gambas branch" be an issue? The gambas branch may be kept as it is, considering it has historical values as you said.

> The other issue is, I'm sort of expecting canonical to drop python 2.7 on the livecd in either 16.04 or 16.10, so there's kind of a need to move towards python 3 and qt5.

From news I follow on 16.04, the release [planned to include Python 3 only](https://wiki.ubuntu.com/Python/FoundationsXPythonVersions). Although, this is subject to changes until the point of FeatureFreeze; This means Feb 18 according to [this schedule](https://wiki.ubuntu.com/XenialXerus/ReleaseSchedule). According to [this Wiki](https://wiki.ubuntu.com/Touch/QtTesting), Qt 5.5 might be the default.

> That's assuming @clearkimura feels like keeping the old repo around and in a zombie state; perhaps setting a gmail filter to mark them read...

This is why I thought transfering the repo is better. Sure, you may feel uneasy to take over (perhaps due to messy branches or the untidy wiki (whoops, that's my bad). Then again, the pros outweighs the cons.

And no, I don't feel like keeping the repo to myself. My only concern is to clean up the documentation "mess" I have made.

> @clearkimura is the remote named 'upstream' for now.

Um, I am not sure what it actually means here... The remote a.k.a the fork is 'upstream', I think? So no need to transfer the repo after all?

Kindly clarify as questioned above.

P.S.: If @kamilion concern is the already created fork named "customizer" (lettercase sensitivity which may conflict during the repo transfer), the created fork may be renamed (this is possible in the repo "Settings" tab) to something else i.e. "customizerdev" before doing the repo transfer.

**Comment by fluxer** [comment]
@clearkimura
Actually I consider this a quick reply.

@clearkimura , @kamilion 

> Even after the repo transfer, development only takes place in master branch (or newly created branch, if any). So why would "touching the gambas branch" be an issue? The gambas branch may be kept as it is, considering it has historical values as you said.

I don't think that this is an issue too. Final decision is up to @kamilion tough (or any future developer in that matter).

> From news I follow on 16.04, the release planned to include Python 3 only. Although, this is subject to changes until the point of FeatureFreeze; This means Feb 18 according to this schedule. According to this Wiki, Qt 5.5 might be the default.

The way I see it it does not matter. Python 2.7 branch may not be shipped by default on many distributions these days but it will stay for quite some time in their repos I believe.

> This is why I thought transfering the repo is better. Sure, you may feel uneasy to take over (perhaps due to messy branches or the untidy wiki (whoops, that's my bad). Then again, the pros outweighs the cons.

Agreed about repo transfer.

> And no, I don't feel like keeping the repo to myself. My only concern is to clean up the documentation "mess" I have made.

I feel the same about the "mess", yet, I'm not keen to do so. Especially about the GUI. I can give a few pointers to where one should look for code that needs improving but that's about it. Me and @clearkimura wanted to deal with this issue some time ago but never ended the initiative - and that's my bad. https://github.com/clearkimura/Customizer/wiki/Developer-notes was supposed to be the solution and first stop for the future developer(s) so maybe I can put some more info on it if requested and assuming @kamilion will have use for it.

> Um, I am not sure what it actually means here... The remote a.k.a the fork is 'upstream', I think? So no need to transfer the repo after all?

For his local copy of the git repo he has setup a second remote which he uses to sync with your repo @clearkimura . Say, if I or you make a commit to clearkimura/Customizer then he can do `git pull upstream master` and sync his local copy and then push the changes to his fork.

> P.S.: If @kamilion concern is the already created fork named "customizer" (lettercase sensitivity which may conflict during the repo transfer), the created fork may be renamed (this is possible in the repo "Settings" tab) to something else i.e. "customizerdev" before doing the repo transfer.

I really have no idea what will happen. You may bite the bullet @clearkimura and give it a shot (to transfer the repo to @kamilion ) if he wants to or (my recommendation) turn to help from GitHub support before we end up with a real mess. Consider the second option if @kamilion cares about the history of the project.

Cheers!

**Comment by kamilion** [comment]
I have no real preference. 

At the moment, I have a repo with a lowercase c, with a clone of the wiki as-is, and the readme pointers from github.com/fluxer/Customizer changed to github.com/clearkimura/Customizer (which was already taken care of on github.com through automated redirection from fluxer -> clearkimura, through a previous repo reassignment) along with a few minor patches.

The only _current_ difference between my repo and @clearkimura 's is the Issues, which are mostly legacy issues that were either resolved and closed, or simply remained open for long time spans.

As long as @clearkimura does not click delete on his repository, the "old" issue tracker items will remain, and I can simply link to https://github.com/clearkimura/Customizer/issues from the new wiki pages under a "Historical issues" link. In this context, I can remove the remaining branches from my fork of the repo, leaving them to continue existence in the 'old' repo.

We have a nice fresh issue tracker/pull request slate, which (if the situation remains as it is) will contain only python-related issues and pull requests.

So, to tally the options:

Option A: @clearkimura could self-service reassign the repo to @kamilion
Option B: Github support could copy the Issues (and subscribers, yikes!) from @clearkimura to @kamilion
Option C: We could create a github organization, assign membership, and migrate the canonical URL for the project to that location. (I've already added the contributors here to my repo)
Option D: New Issues/PRs lists, No further planned migration, A patch to https://github.com/clearkimura/Customizer/blob/master/README.md  providing a forward pointing link to https://github.com/kamilion/customizer and stating @clearkimura has ceased development (for now) but retains the writable branch (which we could always merge from/to).

My hat's on option D for the moment unless convinced otherwise, I guess. Path of least resistance.

**Comment by kamilion** [comment]
Incidentally, I make an lubuntu livecd at https://github.com/kamilion/kamikazi-core which includes Customizer as part of it.
https://github.com/kamilion/kamikazi-core/blame/master/resources/buildscripts/xenial/19-add-iso-customizer.sh

It's built with Customizer's hooks.
https://github.com/kamilion/kamikazi-core/tree/master/resources/buildscripts/xenial

As it is, you can download one of my ISOs from the Releases page, or one of the USB images, and have your own Customizer ready to use, running in-ram from TMPFS.

When Canonical removes python2.7 from their ISO generation seeds, I don't intend on adding it back into my own ISOs. As of my last series of commits in september, Customizer works on python3.2+ and python2.7 just fine. The bigger problem is including the QT4 runtime, as almost all of the rest of my ISO tools are built against QT5. It's nearly 75MB I can shave off my ISO.

I've also had a look at what it would take to include a SECOND gui based on QT5 and a THIRD gui based on gtk+. A new 'customizer-gui' script can inquire as to what toolkit is around, and run the proper GUI as root, using the proper method of privilege escalation available. (pkexec, gksudo...)

See: https://bitbucket.org/ubuntu-mate/ubuntu-mate-welcome  which is a modern fork of https://github.com/Antergos/antergos-welcome

Imagine I relabel the buttons to the same as our current QT4  'six-pack' action arrangement.

ubuntu-mate-welcome can install packages, too, using code from
http://blog.schlomo.schapiro.org/2014/01/apt-install.html
which could easily be adapted to be used as an in-chroot hook to perform package transforms.

Code to impliment a new hook system could be sourced from
https://github.com/fullstory/pyfll
See here to view their package transforms:
https://github.com/fullstory/pyfll/tree/master/packages

**Comment by fluxer** [comment]
@kamilion I'm not going to try to convince you anything. I've stated my recommendations on this matter and I'm not going to repeat them to death.

No hard feelings. Good luck, I'm signing off.

**Comment by kamilion** [comment]
@fluxer No worries; I'm gonna be wrenching on Customizer improvements anyway. What URL git remembers to pull and push to doesn't really bother me.

It's pretty much up to whatever @clearkimura decides is the best way to deal with "stepping down" from maintainership is. Many paths are open; choose which shall be walked.

(And you both still have commit access on my repo; so just because you're not wearing the 'official maintainer' hat doesn't mean you can't still push a fix in yourself if needed, I don't mind a bit.)

**Comment by ghost** [comment]
@kamilion @fluxer 
I have thought about this carefully for some time and I think I have reached my decision. As usual, my replies are after the quoted text. The summarized decision will be written at last.

> Option D: [...] A patch to https://github.com/clearkimura/Customizer/blob/master/README.md providing a forward pointing link to https://github.com/kamilion/customizer

Already done: [Updated README.md](https://github.com/clearkimura/Customizer/blob/master/README.md) and also [Wiki Home](https://github.com/clearkimura/Customizer/wiki).

> [...] and stating @clearkimura has ceased development (for now) but retains the writable branch (which we could always merge from/to).

Um, this is not entirely true. Because once I have done cleaning up the documentation, my contribution to this project since late-2011 will finally make a full stop.

Now remaining 3+1 items in [my todo list](https://github.com/clearkimura/Customizer/issues/86).

> My hat's on option D for the moment unless convinced otherwise, I guess. Path of least resistance.

I came to agree with option D, with one condition: **Don't duplicate the Wiki**

This follows the @kamilion opinion:

> [...] I can simply link to https://github.com/clearkimura/Customizer/issues from the new wiki pages under a "Historical issues" link. In this context, I can remove the remaining branches from my fork of the repo, leaving them to continue existence in the 'old' repo. [>]

Yes, you can quote or simply link to relevant pages. But _not_ duplicate.

> [>] We have a nice fresh issue tracker/pull request slate, which (if the situation remains as it is) will contain only python-related issues and pull requests.

If issues/pull requests are treated so, then the same should apply for the Wiki.

> Incidentally, I make an lubuntu livecd [...] I've also had a look at what it would take to include a SECOND gui based on QT5 and a THIRD gui based on gtk+. [...]

In short, there are many upcoming changes that will happen in forked repo. This is another supporting reason that the 'old' Wiki should _not_ be duplicated.

The 'old' Wiki will _not_ contain any relevant documentation for changes that will happen in forked repo. The 'new' Wiki shall take the role of covering these upcoming changes. Whatever still relevant, you can always quote and link back to 'old' Wiki.

**Fix the duplicate**

The solution is simple: Delete all duplicated pages that you have cloned from 'old' Wiki. As for several common pages i.e FAQ you can link back to 'old' FAQ and add only new questions instead.

This duplicate issue is a déjà vu to me and @fluxer (if he still remember). It's the second or third time happened throughout our contributions in this project. It is a bad idea to duplicate documentation (this is _not_ same as mirroring). And this is a mistake that future contributors should never make.

---

**Side note**

> (And you both still have commit access on my repo; so just because you're not wearing the 'official maintainer' hat doesn't mean you can't still push a fix in yourself if needed, I don't mind a bit.)

Thanks, I will probably need it (to edit my contribution status in the forked README.md) once I finished cleaning up the documentation for 'old' WIki.

---

**The decision**
- As suggested by @kamilion this project repository remains as it is. No further migration.
- The 'new' Wiki shall contain no duplicate pages and shall create its own pages; Only quote and link to 'old' Wiki when necessary i.e. FAQ page.
- From now on, I consider the existing repository as "old stable" (as stated in the updated README.md and Wiki Home).

**Comment by kamilion** [comment]
No problem. "Old stable" was exactly the result I was looking for.

I hadn't seen #86 before, so I'll read over it tonight and see where I can help out in clearing your remaining todo items.

Ninja edit: I also didn't fully read #70 where @clearkimura self-describes as a documentation person, not a developer. Whoops! 

For right now I'll retain my duplicate of the wiki at /kamilion/customizer.wiki.git and rebuild the documentation myself from the existing information, and some information that (at the moment) only exists within issues on @clearkimura 's repo, such as the list of ISOs we know are compatible.

At the moment, I do not want a "Documentation coming soon" message in an otherwise empty Home.md file. I DO understand your feelings about the wiki being duplicated and will comply when I have a moment free to work on it in the next few weeks.

## 

issue one: Github wikis are separate git repositories. Finish up your changes to the wiki and I'll pull them in to the new master in my repo. Thank you for the style guide in #86 as it will be useful to me.

issue two: For some reason, Github does not notify people when text inside of an issue component changes.
Ninja-editing existing issues with new information doesn't actually alert anyone unless you also post a comment at the end. The edits you're making here on #70 and on #86 are not alerting anyone.

## _THIS IS NOT A PROBLEM, just a reminder of what the behavior is._

Now that I know about the issues getting edited; I'll pin the tabs in my browser so I can watch for changes to them.

**Comment by ghost** [comment]
@kamilion 
Glad to hear that the decision is passed. The "path of least resistance", as you said.

> I hadn't seen #86 before, so I'll read over it tonight and see where I can help out in clearing your remaining todo items.

Small help is nice, but keep the motivation to yourself mostly. You will need it the most for improving Customizer in coming days; Start with in-line documentation within the code. Don't "waste" your energy to work on something users don't care to read i.e. user guide. Keep Wiki to minimal. With just handful of active members, sparing energy is more important than satisfying users' demands.

> Ninja edit: I also didn't fully read #70 where @clearkimura self-describes as a documentation person, not a developer. Whoops! 

Exactly: "didn't fully read". Typical users don't bother to read the instructions carefully; Usually not much _relevant_ details when reporting issues. Above all, typical users more often than not, will not bother to suggest improvements (based on my observations, but could be false assumption).

> issue one: Github wikis are separate git repositories. Finish up your changes to the wiki and I'll pull them in to the new master in my repo. Thank you for the style guide in #86 as it will be useful to me.

I hope I can work on the last few items within the next few weeks... The "style guide" is the result of few months of participation at Q&A sites and a lot of trials and errors (noticed any absurd number of revisions for some Wiki pages?). It's more like suggestions of the best practice. It is good for **Wiki**+**Markdown** use on GitHub. It is _bad_ for a user guide, which requires more sophisticated styles and other issues.

> issue two: For some reason, Github does not notify people when text inside of an issue component changes.
> Ninja-editing existing issues with new information doesn't actually alert anyone unless you also post a comment at the end. The edits you're making here on #70 and on #86 are not alerting anyone.

There is no good reason to alert other people to notify edits that I'm making. When I think it is necessary to notify, then only I will write as new comment. If GitHub alerts for every single edits that people make, it's more like an annoyance and waste of bandwidth. I had experienced this once; Had enough of it.

> Now that I know about the issues getting edited; I'll pin the tabs in my browser so I can watch for changes to them.

There is already a way to discover the latest changes in GitHub issues. Go to the [GitHub issues](https://github.com/clearkimura/Customizer/issues), In the shaded header row, click on **Sort** > **Recently updated**. The page will refresh to [this URL](https://github.com/clearkimura/Customizer/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and sort the issues according to updated timestamp, including edits made within an existing comment.

GitHub.com is now more "clever" than it was back then, circa 2012. Say, your web browser has two GitHub pages opened in respective tabs within the same window. Login from one tab; Once you login, you switch to the another tab, then GitHub page will detect the login session and a notification bar will appear at top of page, asking to refresh the page. Brilliant design.

I tried to keep things short, and I hope this is sufficient for your understanding. I shall keep in touch for the next few weeks, until the documentation clean up is finished.

**Comment by kamilion** [comment]
Actually, when I clicked on the tab, github had already refreshed the page in the background; I only saw the gmail notification popup for a moment before I clicked over here.
Thanks for the pointer at the recently updated link; that'll come in handy.

## 

Yes, it's quite the case that documentation is often overlooked.
Personally, I was already deeply involved in the mechanics of the boot structure and how casper worked before running into Customizer, as Ubuntu-Builder's maintainer had retired (which was another gambas2/3 utility doing almost the same thing as Customizer) and stopped providing updates. I contributed some patches for the shellscripts it called to fix some issues, but was never able to get the package updated, so I too gave up on Ubuntu-Builder when I found Customizer, because I didn't feel like maintaining code written in BASIC. Those packages are still in my ubuntu PPA.

Thanks to the python rewrite of Customizer; I have a tool I am comfortable with. 
I've been learning python for a long time; but I'm still just a hobbyist, far from a seasoned developer.

I still havn't bothered even looking at the wiki because Customizer "is so straightforward" to someone like me that was already doing work in live CDs.

However; I know from interacting with melodie on IRC that not everyone has experience in knowing how all of this works; or spending the time necessary to developing an understanding of it.

They simply want a tool that works when you click the button. (So do I.)

Off to read the wiki for me.

**Comment by ghost** [comment]
@kamilion 
Hi, there! I'd like to inform you about two things as below.
1. Permanently deleted "CustomizerMedia" repository
   
   This repository has been holding screenshot images temporarily for convenience, but now made redundant. Since you might have forked the Wiki prior to the [initial discussion](https://github.com/clearkimura/Customizer/issues/70#issuecomment-172203743), the screenshot images are still linked to this now-deleted repo. The only effect due to this is, the screenshots in the forked Wiki will be missing.
2. The last page remaining to complete clean up
   
   As today, "First guide" is the only remaining page that will require revision from me. Among the pages in the old Wiki, there are two articles I had written for generic reading (rather than reference): [Definition](https://github.com/clearkimura/Customizer/wiki/Definition) and [Rebranding](https://github.com/clearkimura/Customizer/wiki/Rebranding). The latter is what I have written today.

When I have completed the documentation clean up, I will inform you again.

**Comment by kamilion** [comment]
Okay:

```
ubuntu@kamikazi-builder-1604:~/git/customizer.wiki$ git pull upstream master
From https://github.com/clearkimura/Customizer.wiki
 * branch            master     -> FETCH_HEAD
Updating 96c8115..c98f7ab
Fast-forward
 Archive.md                | 22 +----------------
 FAQ.md                    |  4 ++--
 Features.md               | 44 +++++++++++++++++-----------------
 Home.md                   |  6 +++--
 Issue-submission.md       | 60 ++++++++---------------------------------------
 Manuals.md                |  6 ++---
 Rebranding.md             | 51 ++++++++++++++++++++++++++++++++++------
 Screenshots.md            | 22 ++++++++++-------
 Supported-host-systems.md |  5 ++++
 Tutorials.md              | 23 ++++++++++--------
 10 files changed, 118 insertions(+), 125 deletions(-)
ubuntu@kamikazi-builder-1604:~/git/customizer.wiki$ git push origin
Password for 'https://kamilion@github.com': 
Counting objects: 108, done.
Delta compression using up to 12 threads.
Compressing objects: 100% (50/50), done.
Writing objects: 100% (108/108), 15.24 KiB | 0 bytes/s, done.
Total 108 (delta 69), reused 97 (delta 58)
To https://kamilion@github.com/kamilion/customizer.wiki.git
   96c8115..c98f7ab  master -> master
ubuntu@kamikazi-builder-1604:~/git/customizer.wiki$ 
```

Your changes have been pulled into my wiki.

**Comment by ghost** [comment]
Since I have finished documentation clean up and last review on Wiki, I will be "not watching" this repo effective today. I will still be notified to any issues I have participated or if I am @mentioned.

Thanks for having me to work on documentation for this project from 2011 until today.

**Comment by ghost** [comment]
Since late August 2016, I have assigned myself as 'interim maintainer' for my own reason to self-learn about Debian packaging and bit of Python and Qt (to clean up GUI). My role will end with the release of 4.2.0, which I hope to achieve sometime soon, before I start looking for a new permanent job.

To this date, we have:
- the fork created by @kamilion that is what I consider as the official fork (among 49 forks on GitHub); Migration to Python 3 and Qt 5 will be handled by the fork in near future;
- this "old stable" repository that is currently maintained by @clearkimura myself as 'interim maintainer', to fill the 'gap' before transferring to the future owner and contributors, anytime later ^1

^1 Regarding repo transfer to future owner, as well as the role of "old stable" in the future, this shall be discussed as separate issue, which may be created later (when the time comes, if necessary)

Above all, since we do have maintainers for Customizer in the official fork and "old stable", albeit less active nowadays, I suppose this issue can now be closed for good.

P.S.: [The readme](https://github.com/clearkimura/Customizer/blob/master/README.md) has been simplified and clearly mentions the fact, since "old stable" [4.1.3](https://github.com/clearkimura/Customizer/releases/tag/4.1.3).

**Comment by ghost** [comment]
As late Jaunary 2017, the official fork was removed after all. This "old stable" repo will be transferred to fork maintainer. The role of 'interim maintainer' therefore will end here.
