### ISSUE TITLE
Customizer devel branch needs testing and feedback

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#73]
The devel branch has received some updates from @fluxer since several days ago. Initial testing has been done by @clearkimura for CLI and latest devel branch CLI and partially working GUI tested by @fluxer however limited.

**UPDATE** Since late November 2014, some known issues had been resolved. The GUI are now working well and good enough for basic use.

This devel branch is particularly important for those whom wish to customize recent releases of Ubuntu (especially 12.10 or newer) because existing master and gambas3 branches might not fully support recent releases of Ubuntu.

To further polish the devel branch, we need feedbacks from other users or volunteers.

For those whom interested and willing to participate to do testing, kindly visit [Customizer devel branch](https://github.com/clearkimura/Customizer/tree/devel) for requirements and installation details. You will have to dowload the code and install it manually.
##### How to install devel branch for testing
1. Visit the [devel branch](https://github.com/clearkimura/Customizer/tree/devel). In the right column area, click on **Download ZIP** button. The ZIP file will be saved to your **Downloads** folder by default.
2. Open the Terminal, and type below command and press **Enter** key for each line (to traverse directory, extract ZIP file, traverse into extracted folder)
   
   ```
   cd Downloads
   unzip *-devel.zip
   cd *-devel
   ```
3. In Terminal, type the command below and press **Enter** key. At this stage, if you see any error as described in issue #72 proceed to step 4 to install dependencies. Else, skip to step 5.
   
   ```
   make && sudo make install
   ```
4. In Terminal, type the command below and press **Enter** key. Note that after installing these dependencies, repeat step 3 again for successful install.
   
   ```
   sudo apt-get install make binutils gcc g++ python2.7 python2.7-dev python-qt4 pyqt4-dev-tools squashfs-tools xorriso x11-xserver-utils xserver-xephyr qemu
   ```
5. Finally, run Customizer. For CLI, type `sudo customizer -h` and press **Enter** key. For GUI, you can find a new entry named **Customizer** in application menu.
##### How to update

For users who had installed earlier version of devel branch, you just need to download again the ZIP file from current devel branch, unpack, then follow step 2, 3 and 6 as explained above.
##### How to feedback

First of all, if you are using GUI, you should run Customizer in Terminal by typing `pkexec /usr/sbin/customizer-gui` (or try `sudo customizer-gui`) and press **Enter** key. This way, you can see output log in Terminal and GUI at same time. Copy the output log messages and paste into your feedback.

If the output log didn't show anything relevant, you are encouraged to include screenshots of whole Desktop or Customizer windows and error dialogs only.

To submit your feedback, open a [new issue](https://github.com/clearkimura/Customizer/issues/new). You may leave a comment below with a link to the new issue to indicate the new issue belongs to devel branch.

Discussion shall take place at the newly created issue page (don't discuss here; comments in this page is just to hold links to issues for devel branch).

Last updated: 2014-12-11

**Comment by fluxer** [comment]
Just wanted to let you know that the GUI is complete, improvements such
as exceptions catching in more places can be made but I think it's OK as it is.

I've attached some screenshots, cheers!

![1](https://cloud.githubusercontent.com/assets/1097244/3943112/771bd450-2588-11e4-8b6d-3aaf02fd179c.png)
![2](https://cloud.githubusercontent.com/assets/1097244/3943111/77022230-2588-11e4-9c4b-7f6af990a59a.png)
![3](https://cloud.githubusercontent.com/assets/1097244/3943110/7700c700-2588-11e4-9a97-5e5be78abc68.png)

**Comment by ghost** [comment]
@fluxer 
Successfully installed latest devel branch, updated instructions and some text as above. What is more, the devel branch has first feedback filed as issue #74.

**Comment by ghost** [comment]
@fluxer 
While looking into issue #57 using devel branch (commit 4cda0be), I accidentally discovered several other issues which I see as non-critical to users.

It's related to old issues; qemu and compression format. Could be just issue on my side. I'd be upgrading to latest devel branch (commit 100b6b5) to clarify these issues.

However, I am not going to report any soon, due to lack of testing and time.

**Comment by fluxer** [comment]
@clearkimura 
The compression format issue I suppose is caused when squashfs-tools is older than 4.2 which seems to be the case only on Lucid that is no longer supported. I can add the workaround to the devel branch but is it worth it?

I have not faced issues with qemu, I've tested it on custom linux setup with qemu 2.0.0 and 2.1.1. Is the issue you encounter the same as in #59?

> However, I am not going to report any soon, due to lack of testing and time.

Oki doki. If you can let me know what exactly is wrong with it I will most likely look into it.

**Comment by ghost** [comment]
@fluxer 

> It's related to old issues; qemu and compression format. 

Apologies for my misunderstanding comment.
I suppose I had summarized too short..

The compression format is _not_ that issue with Lucid release. Because I don't test with 10.04 Lucid Lynx anymore due to no longer supported, as you said. As for qemu issue, it is also not same as mentioned issue above, but similar result--qemu failed to run either from GUI or CLI.

Above all, these are the reason why I didn't quote the past issue.

> If you can let me know what exactly is wrong with it I will most likely look into it.

Thanks for your continual support! I will certainly help in any way I can.

Don't worry much about these, because as I mentioned earlier, this may be just on my side. I don't think most users aware; and these issues also probably won't get in their way to build remix.

**Comment by fluxer** [comment]
@clearkimura 
Do you have qemu-kvm installed? Check this out: http://packages.ubuntu.com/it/precise/amd64/qemu-kvm/filelist

**Comment by ghost** [comment]
@fluxer 
I have created a new issue to discuss on QEMU for devel branch, filed under issue #78 just now.

**Comment by ghost** [comment]
While looking into the mentioned issue, I discovered that "apparently gambas3 and devel branches can co-exist with same work directory". I find this useful for troubleshooting different branch using the same extracted ISO that is being customized. No problem with this.

However, to avoid any complication, I decided to create separate working directory for each branches under `/home` directory for testing next time onwards.

Then.. I think I have found another issue for devel branch. Not again.. sigh. This is considered minor, but troublesome. Typical user with default working directory wouldn't notice (me too, until just now).

**Comment by fluxer** [comment]
So you think that the default working directory should be changed for the devel branch?

**Comment by ghost** [comment]
@fluxer 
No, something to do with undefined variable. See newly created issue #79 filed just now.

**Comment by ghost** [comment]
The aforementioned issue #80 will follow up later with relevant screenshots and details. Need to reproduce the issue again to clarify.

Meanwhile, I had submitted two other issues #81 and #82 with higher priority, because these are affecting core features: **Desktop** and **Clean**.

**Comment by ghost** [comment]
Issue #78 has been resolved now. At this stage, it is good enough for basic usage but still lack of testing and feedbacks from end users.

**Comment by ghost** [comment]
With the recent pull request Devel #84 , the **devel** branch now has been merged into **master** branch. Therefore, this issue is now rendered obsolete.
