### ISSUE TITLE
Customizer supported ISO images

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#76]
**Revised on 2015.09.17**

This issue has been created following the concern of changes in recent Ubuntu-based ISO images, especially Ubuntu Mini Remix (UMR) ISO images.

Since 13.10 release, it has been reported on [this Ubuntu Launchpad thread](https://answers.launchpad.net/ubuntu/+source/debian-cd/+question/240037) that the `livecd-root` bash script had been removed (probably from ISO image content or default packages).

The original custom shell script in `livecd-rootfs` [has been moved] to the newer live-build system from Debian (formerly called live-helper).. This only affects Oneiric and later releases. More details in [this debian-live mailing list back in 2011](https://lists.debian.org/debian-live/2011/06/msg00152.html) and [this stable manual](http://live.debian.net/manual/stable/html/live-manual/managing-a-configuration.en.html).

Following this change, UMR faced difficulties to build the base of Ubuntu squashfs without the script. Its recent ISO image is likely built using `ubuntu-defaults-builders` to install just the "base" flavour (minimal + standard metapackages), cited from same thread above.

The current UMR releases are somewhat compatible and usable by Customizer, but it is claimed [to have different ISO structure](https://github.com/clearkimura/Customizer/issues/75#issuecomment-54366596) and [some Live CD features may not work](https://github.com/clearkimura/Customizer/issues/70#issuecomment-51692948).

Besides this, if anyone can suggest other method to build Ubuntu base from scratch (plus can confirm that it is compatible with Customizer), that is also welcomed. I know there is [Ubuntu community page for this](https://help.ubuntu.com/community/LiveCDCustomizationFromScratch), but may not work well for recent Ubuntu releases.

**Comment by ghost** [comment]
**Updated on 2015.09.03**

For recent releases of Ubuntu Mini Remix (notably 14.04 and newer), there are two known features on Live CD that doesn't work by default: `memtest` and `integrity-check`.

The good news is, I have found the way to fix these. Before you begin, note that the following instructions assume that:
- you have already installed latest Customizer from master branch,
- you run Customizer GUI with default working directory `/home`,
- you have loaded UMR 14.04 32-bit ISO image on 32-bit host system,
- you have installed minimal CLI environment to boot minimal Live CD

**IMPORTANT** Make sure you don't mix between "host system" and "chroot system"!
1. In Customizer GUI, click on **Terminal** button to run chroot Terminal.
2. In the chroot Terminal, install `memtest86+` package from main repository via APT.
   
   ```
   apt-get install memtest86+
   ```
3. After finished installing the package, close the chroot Terminal by `exit` command.
   
   ```
   exit
   ```
4. Now run a Terminal on host system (use shortcut keys `Ctrl`+`Alt`+`T` or `Super`+`T`).
5. Create a new directory named `install` in `ISO` directory of chroot system.
   
   ```
   sudo mkdir /home/ISO/install
   ```
6. Copy `memtest86+.bin` file from `boot` directory to the newly created `install` directory and rename to `mt86plus` (Bash command can do this in single line).
   
   ```
   sudo cp /home/FileSystem/boot/memtest86+.bin /home/ISO/install/mt86plus
   ```
7. At this point, if you wish to fix `integrity-check` feature, simply create an empty file named `md5sum.txt` in the same directory as `SHA256SUM` (usually `/home/ISO`) i.e. While still running Terminal on host system, run the following command.
   
   ```
   sudo touch /home/ISO/md5sum.txt
   ```
   
   > In this step, `md5sum.txt` is still an empty file. But when rebuilding ISO, Customizer will auto-detect the existence of this file and will attempt to recreate this file with updated contents. Just prepare the empty file with correct name and the rebuilding process will take care the rest.
8. Finally, in Customizer GUI, click **Rebuild ISO** and try out the created ISO image in a virtual machine such as QEMU or VirtualBox.

When you boot the rebuilded ISO, you will see small logo appears at bottom of screen. Press **Enter** key once and boot menu will be shown. Select **English** as language.
- To run `memtest` feature on Live CD, use arrow keys to select **Test memory** menu. Then, press **Enter** key again. You should be seeing Memtest86+ running in blue color screen shown below.

![screenshot - 09202014 - 065620 pm](https://cloud.githubusercontent.com/assets/1223304/4345218/0b5173c8-40be-11e4-8190-76e63b57cc38.png)
- To run `integrity-check` feature on Live CD, use arrow keys to select **Check disc for defects** menu. Then, press **Enter** key again. You should be seeing splash screen with a line of message. To see the full message, press **Esc** key and you will see something like below.

![c411-rebuild-prepr-umr-testvm-md5](https://cloud.githubusercontent.com/assets/1223304/9665446/ee61b91c-525f-11e5-9368-3eb244951e5d.png)

That's it, you have now fixed both `memtest` and `integrity-check` features on Ubuntu Mini Remix!

**Comment by fluxer** [comment]
UMR has its own issues, you can fix them and release ISOs based on it but for an example with memtest fixed and/or updateds as a good start for use with Customizer. Other than that Linux Mint and official Ubuntu releases should work fine.

Hint: compare Ubuntu vs UMR or Mint vs UMR ISO structure, observe difference and experience issues.

**Comment by fluxer** [comment]
And btw, last activity on relinux code dates from 2013-10-28. It will probably work on new releases (e.g. 14.10) as much as Customizer gambas2/gambas3 branches do - with many issues. Remastersys seems dead end too.

**Comment by hreikin** [comment]
he recently posted this on his blog : 

http://lkubuntu.wordpress.com/2014/09/14/im-quitting-relinux/

so unless someone takes the source and updates it then its going to die soon :(

**Comment by ghost** [comment]
@fluxer 
I will try to compare official vs UMR ISO image files, as you hinted. Though, I may only compare between LTS releases only.

@hreikin  
I read the post earlier.. Too bad we lose another alternative. Just like the startups businesses in overseas, open source projects emerges and falls after short while.

---

Anyhow, the author of relinux suggest to use 0.3a3 release. "Do not use 0.4" because it has not been tested or coded well apparently, as quoted from [relinux at launchpad](https://launchpad.net/relinux/+announcement/12365).

As for remastersys, circa 2008 was the peak of popularity. Later, it has been removed from repositories for good (not sure since which release). Someone did manage to keep or maintain in [this untrusted PPA](https://launchpad.net/~mutse-young/+archive/ubuntu/remastersys) for precise and trusty releases. I have never tried yet and I probably won't.

Another fork of remastersys is "os4systemimage" or "System Imager", supported by funding or something like kickstarter project. They have their [Sourceforge.net project page](http://sourceforge.net/projects/os4systemimage/) and [blog](http://system-imaging.blogspot.com/) for updates. Not quite open source project anymore.

**Comment by ghost** [comment]
The problem that some of us think might happen became reality. Issue #102 is only the beginning. 

With recent releases, from 15.04, upstart has been replaced with systemd for boot and services manager. This may have broke the chroot experience.

That is just my skeptical guess, but I base on information found on the Web.

And even the chroot issue could be resolved somehow, there might be other problems in future because systemd doesn't just take care of boot process but extends to other parts of system, I heard (not sure what are the "other parts" systemd intends to handle).

As 15.04, it is easy to switch between upstart and systemd (just remove and install packages) and Ubuntu has already [explained on their Wiki](https://wiki.ubuntu.com/SystemdForUpstartUsers). But I am unsure if this will resolve the issues...

P.S.: My remastering venture might end with 14.04 release.

**Comment by ghost** [comment]
Don't be mistaken with my previous comment above. It is _not_ because Customizer. It is because the changes that is happening in Ubuntu development.

Next major change in foreseeable future would be, DEB-based might be replaced with [Snappy-based](http://askubuntu.com/questions/605066/what-is-snappy-ubuntu-core). I haven't read in detail yet, so not sure how "different" it would be to existing system.

So I might move on to other Ubuntu-based distro or similar by next year.

**Comment by ghost** [comment]
While looking into pull requests from @kamilion I realized there is an easy way to fix `integrity-check`. See my updated comment [at above](https://github.com/clearkimura/Customizer/issues/76#issuecomment-56266140).

**Comment by ghost** [comment]
To this date, Customizer 4.1.1 release (as commit 2a7864f) has better support for handling ISO images of Ubuntu 15.04 and newer releases. Thanks to @fluxer and @kamilion for the support!

Edit: See [this comment](https://github.com/clearkimura/Customizer/issues/107#issuecomment-137029731) for information regarding recent compatibility issue.

**Comment by ghost** [comment]
This issue shall be closed, because "old stable" will be deprecated.

For future issues, please submit to official fork: https://github.com/kamilion/customizer

P.S.: The official fork was removed, then "old stable" repo will be transferred to fork maintainer.
