### ISSUE TITLE
Could not read from the boot medium! System halted

### ISSUE THREAD

**Issue by winhex** [kamilion/customizer#8]
Hi After rebuilding original iso xubuntu-14.04.5-desktop-i386.iso without any changes I have this error in virtualbox:
> 
FATAL: Could not read from the boot medium! System halted.
> 

Host system is Xubuntu 16.04.1 32bit.
I tried to do it on other computer with Xubuntu 14.04 32 bit and got the same error.
Pls, help me to resolve this problem!

**Comment by winhex** [comment]
I'm sorry, it's my mistake!

**Comment by kamilion** [comment]
Can you comment on what mistakes were made to result in that?

**Comment by winhex** [comment]
> Can you comment on what mistakes were made to result in that?
> 

Of course. Before starting the VM, I was not convinced that the ISO image is really connected to the VM. When I did this, the problem disappeared. It's simple)

**Comment by kamilion** [comment]
Ah, a beginner's mistake, but a good one to keep others from falling into!
The email notification of your issue also triggered me to traverse the issue queue and apply a patch which fixes the display of critical error messages. 
Only three little characters, {0}, but in a very important place! *laughs*
(and of course, it was my own mistake; in my earlier patches to allow python3 support.)

So, thanks for that, and hope your ISO works out the way you want!

If you need some inspiration, I use Customizer in my other project, adding the Xen hypervisor to Lubuntu.
https://github.com/kamilion/kamikazi-core/tree/master/resources/buildscripts/xenial
