### ISSUE TITLE
lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease': No such file or directory

### ISSUE THREAD

**Issue by fsfarah** [kamilion/customizer#85]
I got the following error during `make`
`lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease': No such file or directory`

I'm using Ubuntu 14.04 Dekstop

**Comment by fluxer** [comment]
That would be a problem with the Qt4 packages I guess. Try re-installing them, I think lrelease was part of qt4-tools or something like that.

**Comment by fsfarah** [comment]
Do you mean qt4-dev-tools? that's another 100MB of archives, doesn't sound
very convenient for a relatively small app, is there any alternative?
Thanks

**Comment by fluxer** [comment]
Yes, that should be it. And there is no alternative as far as I know. You can however trick the build system that lrelease is present:

`make LRELEASE=true`

But the application will not be translated.

**Comment by fluxer** [comment]
Since this is now related to Customizer per-se I mark this issue as invalid. I will leave the issue open in case someone wants to enhance the build system and make the translations optional. The pending label will be removed once the reporter gets this sorted out.

**Comment by fsfarah** [comment]
Ok,

I tried make with LRELEASE=true
make install gave this error:
`install: cannot stat 'tr/*.qm': No such file or directory
make: *** [install-gui] Error 1`

**Comment by fluxer** [comment]
```
make LRELEASE=true
touch tr/fake.qm
sudo make install
```

**Comment by ghost** [comment]
I am running 14.04 32 bit host system and also encountered same issue.

Even @fsfarah mentioned that `qt4-dev-tools` requires more than 100 MB of installation, not really true from my findings.

The `lrelease` program is handled by `qt4-linguist-tools` package. The former package may not be required, although I did install without recommended packages.

To summarize, below is my installation log (with details removed):

```
$ sudo apt-get install qt4-dev-tools --no-install-recommends
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libqt4-sql-sqlite
Suggested packages:
  libqt4-dev qt4-doc-html
Recommended packages:
  qt4-designer qt4-doc
The following NEW packages will be installed:
  libqt4-sql-sqlite qt4-dev-tools
0 upgraded, 2 newly installed, 0 to remove and 358 not upgraded.
Need to get 3,871 kB of archives.
After this operation, 8,864 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
...
```

At this point, the issue is still happening. So I proceeded to install the subsequent package.

```
$ sudo apt-get install qt4-linguist-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  qt4-linguist-tools
0 upgraded, 1 newly installed, 0 to remove and 358 not upgraded.
Need to get 827 kB of archives.
After this operation, 2,792 kB of additional disk space will be used.
...
```

So, total install package is about 11 MB or less. And it fixed this issue for good.

P.S.: The install size above is applicable to users on freshly installed Xubuntu 14.04 32 bit. Unless `--no-install-recommends` option is specified, install packages will be more than 100 MB in size.

**Comment by fluxer** [comment]
@clearkimura 
The size of the packages to be installed will be different for most setups depnding on what is currently installed. For an example, if someone is prefering GTK+ over Qt applications he will, most likely, not have all Qt libraries installed and having the developer tools would be even more rare.

**Comment by loggerJK** [comment]
@clearkimura 
Thank you!!!!
I solved my problem!!!

**Comment by CapacitorSet** [comment]
If anyone came across this thread while googling the error message: the correct package for this is `qt4-linguist-tools`.

**Comment by gautamsreekumar** [comment]
@CapacitorSet i don't think that is the correct package. i got the same issue with GNU Octave and that did not resolve the issue.

**Comment by phoenix-programmer** [comment]
Just came here trying to compile another project and getting that message.
`lrelease: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lrelease': No such file or directory`

As I have qt5 I thought that by creating a symlink to /usr/lib/x86_64-linux-gnu/**qt5**/bin/lrelease it should work:
`sudo ln -s /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease /usr/lib/x86_64-linux-gnu/qt4/bin/lrelease`

and it worked, and it was good, and everybody was happy and caring about each other, and shared cannabis with those who liked and lived without authorities, without private properties and without mercantilism.

**Comment by kamilion** [comment]
@Diego1977 You should really be using `make PYTHON=python3 PYQT=5; sudo make install` or `make PYTHON=python3 PYQT=5 deb` instead of hacking around it with symlinks.

**Comment by miroi** [comment]
I came around this issue as I have something similar
~~~
lconvert: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/lconvert': No such file or directory
~~~
although the package is installed...
