### ISSUE TITLE
make deb command provides a "4.1.0" package instead of a "4.1.2"

### ISSUE THREAD

**Issue by melodie11** [kamilion/customizer#9]
Hello,
I have wget the newest master.tar.gz and after "tar zxvf master.tar.gz" the resulting Customizer-master directory does contain the Changelog with changes done up to the 4.1.2 version. But when the debian  package is created, it names itself "4.1.0". I checked into the package and in it's usr/share/doc/changelog.gz (extracted for the purpose of checking), I found "customizer (4.1.0) unstable ...".

It would be nice to have the package done with the right version number, in order to be able to keep a version of each. 
Thanks for your work!
Best regards,
melodie

**Comment by kamilion** [comment]
Alright, should be calling itself 4.1.2 now, as of the last commit.
