### ISSUE TITLE
Some features returns non-zero exit after using Desktop

### ISSUE THREAD

**Issue by ghost** [kamilion/customizer#90]
I am using Customizer latest commit 94a5558 from **master** branch. I experienced this issue for both GUI and CLI instances (while testing for documentation purpose). Tested using Xubuntu 12.04 and 14.04 32-bit ISO images on Xubuntu 12.04 and 14.04 32-bit host systems respectively.

The issue is, some features will return "non-zero exit" when trying to run the affected features _after_ using **Desktop** feature. This issue will persists as long as current GUI is running.

The affected core features in GUI are: **Edit sources**, **Terminal** in Main tab and **Browse FileSystem**, **Browse ISO** in Extra tab.

Steps to reproduce this issue in Customizer GUI:
1. Select ISO of any official image (must contain Desktop Environment)
2. After extracted by Customizer, click on **Desktop** button to run live session
3. Do nothing, just select "log off" from live session to exit Xephyr.
4. Click on either **Edit sources** / **Terminal** (in Main tab) or **Browse FileSystem** / **Browse ISO** (in Extra tab) and you will see similar "non-zero exit" error dialog will appear.

Similarly, the affected features in CLI are: `-c | --chroot`  and `-x | --xnest` arguments. However, I have witnessed the "non-zero exit" error only once and failed to reproduce this on CLI counterpart.

Above all, this issue is _not_ critical. Because this can be resolved by itself when I exit and rerun GUI again. As long as I don't use the **Desktop** feature first, the previously affected features will remain functional.

So, if I ever use **Desktop** feature while remastering in current GUI, I just need to exit and rerun GUI again. Not a big deal, but may be troublesome for other users.

Another thing I noticed is, this issue only affects the recent commits and _doesn't_ affect the first release of 4.1.0 (commit b75e06a) as I have tested its GUI on the same host system.

**Comment by ghost** [comment]
Example screenshots showing the "non-zero exit" on Xubuntu 14.04 32-bit host system.

Trying to run **Edit sources** feature after running **Desktop** feature:
![xu-1404-c410-bug-after-desktop-mousepad-crash](https://cloud.githubusercontent.com/assets/1223304/6688966/44346cac-ccf2-11e4-82c6-cb7912a1c35f.png)

Exit current GUI, rerun GUI from Terminal and rerun **Edit sources** feature--now working again:
![xu-1404-c410-bug-after-desktop-mousepad-rerun-ok](https://cloud.githubusercontent.com/assets/1223304/6689009/8d83a440-ccf2-11e4-92c9-49f573687870.png)

The host system is fresh installed and no additional packages been upgraded. Only dependencies for Customizer 4.1.0 have been installed and updated.

**Comment by fluxer** [comment]
Make sue you really are using the latest version, the issue should've been fixed with a2eb05fd2ca228b65f9b2b8158b088eb79449839 (do not mind the XDG menus part, it broke again. it's some env. vars issue).

**Comment by ghost** [comment]
@fluxer 
Yes, I am sure.

In fact, I purged existing install, redownload then reinstall again (now this is the "default" method I had updated in the [first guide](https://github.com/clearkimura/Customizer/wiki/First-guide) page).

In short, I used `wget https://github.com/clearkimura/Customizer/archive/master.tar.gz` to download the latest release from **master** branch.

I am getting the same result as reported above. Additionally, I have experienced the **Desktop** feature _cannot_ be run again for second time, unless I close and rerun GUI.

When using GUI, after running **Desktop** and closing it for first time using "log off" menu, then trying to run **Desktop** for second time gives me this:
![xu-1404-xephyr-closed-error](https://cloud.githubusercontent.com/assets/1223304/6731228/6b9c7f54-ce7e-11e4-8a5d-0baa7b846e26.png)

When using CLI, running **Desktop** and closing Live session using "log off" menu gives me this:
![xu-1404-xephyr-closed-error-cli-2](https://cloud.githubusercontent.com/assets/1223304/6731315/0ba8e49c-ce7f-11e4-8400-786a49af6b16.png)

Don't mind about hanging cursor--I press **Return** key and it will show `username@hostname~$` line as usual again.

In contrast, when using CLI, running **Desktop** and but this time closing Live session using "X" button on Window Manager gives me this:
![xu-1404-xephyr-closed-error-cli](https://cloud.githubusercontent.com/assets/1223304/6731238/88d9c130-ce7e-11e4-9776-4169f249474b.png)

The difference between the two interface is, even CLI shows similar error, CLI _doesn't_ prevent me from running **Desktop** or the `-x | --xnest` argument as many times as I want.

CLI always works regardless of error messages. So I suppose this is GUI issue?

**Comment by ghost** [comment]
This is another follow up, to confirm that this issue also affects Customizer installed on Linux Mint host system. Screenshots as below.

When using GUI, run **Desktop** feature at first and select "Log off" in Live session to exit Xephyr, then run **Edit sources** and **Terminal** features in turns and each failed.
![mint17-terminal-broken-after-desktop](https://cloud.githubusercontent.com/assets/1223304/6997703/016f1a6e-dbf9-11e4-82c9-bbd16040fce2.png)

When exit GUI and rerun again, running **Terminal** feature first, it run normal OK.
![mint17-terminal-ok-after-exitgui-rerun](https://cloud.githubusercontent.com/assets/1223304/6997707/122d8872-dbf9-11e4-8bd0-3b0a3e1c2094.png)

Another screenshot showing CLI counterpart is unaffected, as below.
![mint17-chroot-ok-fromcli](https://cloud.githubusercontent.com/assets/1223304/6997745/8aacbac4-dbfa-11e4-98cd-1c102c1418c1.png)

From above screenshot, the CLI has no problem running **Desktop** or the `-x | --xnest` argument followed by running **Terminal** or the `-c | --chroot` argument.

So to clarify again, this issue _only_ persists on GUI counterpart.

Tested latest Customizer 4.1.0 on Linux Mint 17 32-bit host system, using official Xubuntu 14.04 32-bit ISO image on virtual machine.
