### ISSUE TITLE
DNS issue after customization of Lubuntu 14.04.2 with Customizer 4.1.1

### ISSUE THREAD

**Issue by porst17** [kamilion/customizer#97]
I am trying to remaster Lubuntu 14.04.2 using the http://cdimage.ubuntu.com/lubuntu/releases/14.04/release/lubuntu-14.04.2-desktop-amd64.iso

I just unpacked the ISO and rebuilt it again using Customizer 4.1.1. However, networking seems to be broken in the customized ISO while it was working nicely for the original ISO. I turned out, that DNS resolutions is not working anymore. Sending a ping to a `216.58.211.36` (one of the google servers) just works fine.

**Comment by ghost** [comment]
@porst17 
Hi, there! This issue can be traced back to issue #20 that had been reported much earlier.

Apparently, this issue also could happen if normal user upgrades from older to newer release of Ubuntu, according to [this one](http://askubuntu.com/questions/137037/networkmanager-not-populating-resolv-conf) and [another](http://askubuntu.com/questions/134121/how-to-restore-recreate-etc-resolv-conf-files) threads.

**Permanent solution**
By default, Customizer deletes least useful files including the `/etc/resolv.conf` which might be missing on your customized image.

So before you rebuild ISO in Customizer, edit the `/usr/share/customizer/exclude.list` file and remove the line which contains `etc/resolv.conf`. This action should preserve the file as it is.

Edit: Correct me if I was wrong. I just guess based on the issue description, "DNS resolutions is not working anymore". Most probably, I hit the mark.

**Comment by porst17** [comment]
Commenting out the `etc/resolv.conf` line did the job. Is the documented somewhere? I couldn't find it and therefore thought it was a but and created this issue.

**Comment by ghost** [comment]
In the past issue, the user was also using Lubuntu ISO image. And so far, no other users reported similar problem on other distro. So this may be Lubuntu-specific issue.

Supposedly, the distro should re-create the `/etc/resolv.conf` file if it is not there. Therefore this problem does _not_ belongs to Customizer, according to past comments.

I have updated [this part in the First guide](https://github.com/clearkimura/Customizer/wiki/First-guide#3-how-to-run-and-configure-customizer) page to describe the purpose of `/usr/share/customizer/exclude.list` file based on your feedback.

If there is no further issue, you can close this.

**Comment by porst17** [comment]
Ok, so maybe this should be reported at the Lubuntu bug tracker.
